// Generated by jextract

package net.bplo.libs.jimgui.binding;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct ImColor_c {
 *     ImVec4_c Value;
 * } ImColor
 * }
 */
public class ImColor extends ImColor_c {

    ImColor() {
        // Should not be called directly
    }
}

