// Generated by jextract

package net.bplo.libs.jimgui.binding;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ImGuiViewport {
 *     ImGuiID ID;
 *     ImGuiViewportFlags Flags;
 *     ImVec2_c Pos;
 *     ImVec2_c Size;
 *     ImVec2_c FramebufferScale;
 *     ImVec2_c WorkPos;
 *     ImVec2_c WorkSize;
 *     void *PlatformHandle;
 *     void *PlatformHandleRaw;
 * }
 * }
 */
public class ImGuiViewport {

    ImGuiViewport() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        cimgui_h.C_INT.withName("ID"),
        cimgui_h.C_INT.withName("Flags"),
        ImVec2_c.layout().withName("Pos"),
        ImVec2_c.layout().withName("Size"),
        ImVec2_c.layout().withName("FramebufferScale"),
        ImVec2_c.layout().withName("WorkPos"),
        ImVec2_c.layout().withName("WorkSize"),
        cimgui_h.C_POINTER.withName("PlatformHandle"),
        cimgui_h.C_POINTER.withName("PlatformHandleRaw")
    ).withName("ImGuiViewport");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt ID$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ID"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImGuiID ID
     * }
     */
    public static final OfInt ID$layout() {
        return ID$LAYOUT;
    }

    private static final long ID$OFFSET = $LAYOUT.byteOffset(groupElement("ID"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImGuiID ID
     * }
     */
    public static final long ID$offset() {
        return ID$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImGuiID ID
     * }
     */
    public static int ID(MemorySegment struct) {
        return struct.get(ID$LAYOUT, ID$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImGuiID ID
     * }
     */
    public static void ID(MemorySegment struct, int fieldValue) {
        struct.set(ID$LAYOUT, ID$OFFSET, fieldValue);
    }

    private static final OfInt Flags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("Flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImGuiViewportFlags Flags
     * }
     */
    public static final OfInt Flags$layout() {
        return Flags$LAYOUT;
    }

    private static final long Flags$OFFSET = $LAYOUT.byteOffset(groupElement("Flags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImGuiViewportFlags Flags
     * }
     */
    public static final long Flags$offset() {
        return Flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImGuiViewportFlags Flags
     * }
     */
    public static int Flags(MemorySegment struct) {
        return struct.get(Flags$LAYOUT, Flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImGuiViewportFlags Flags
     * }
     */
    public static void Flags(MemorySegment struct, int fieldValue) {
        struct.set(Flags$LAYOUT, Flags$OFFSET, fieldValue);
    }

    private static final GroupLayout Pos$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("Pos"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec2_c Pos
     * }
     */
    public static final GroupLayout Pos$layout() {
        return Pos$LAYOUT;
    }

    private static final long Pos$OFFSET = $LAYOUT.byteOffset(groupElement("Pos"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec2_c Pos
     * }
     */
    public static final long Pos$offset() {
        return Pos$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec2_c Pos
     * }
     */
    public static MemorySegment Pos(MemorySegment struct) {
        return struct.asSlice(Pos$OFFSET, Pos$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec2_c Pos
     * }
     */
    public static void Pos(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, Pos$OFFSET, Pos$LAYOUT.byteSize());
    }

    private static final GroupLayout Size$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("Size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec2_c Size
     * }
     */
    public static final GroupLayout Size$layout() {
        return Size$LAYOUT;
    }

    private static final long Size$OFFSET = $LAYOUT.byteOffset(groupElement("Size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec2_c Size
     * }
     */
    public static final long Size$offset() {
        return Size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec2_c Size
     * }
     */
    public static MemorySegment Size(MemorySegment struct) {
        return struct.asSlice(Size$OFFSET, Size$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec2_c Size
     * }
     */
    public static void Size(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, Size$OFFSET, Size$LAYOUT.byteSize());
    }

    private static final GroupLayout FramebufferScale$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("FramebufferScale"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec2_c FramebufferScale
     * }
     */
    public static final GroupLayout FramebufferScale$layout() {
        return FramebufferScale$LAYOUT;
    }

    private static final long FramebufferScale$OFFSET = $LAYOUT.byteOffset(groupElement("FramebufferScale"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec2_c FramebufferScale
     * }
     */
    public static final long FramebufferScale$offset() {
        return FramebufferScale$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec2_c FramebufferScale
     * }
     */
    public static MemorySegment FramebufferScale(MemorySegment struct) {
        return struct.asSlice(FramebufferScale$OFFSET, FramebufferScale$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec2_c FramebufferScale
     * }
     */
    public static void FramebufferScale(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, FramebufferScale$OFFSET, FramebufferScale$LAYOUT.byteSize());
    }

    private static final GroupLayout WorkPos$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("WorkPos"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec2_c WorkPos
     * }
     */
    public static final GroupLayout WorkPos$layout() {
        return WorkPos$LAYOUT;
    }

    private static final long WorkPos$OFFSET = $LAYOUT.byteOffset(groupElement("WorkPos"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec2_c WorkPos
     * }
     */
    public static final long WorkPos$offset() {
        return WorkPos$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec2_c WorkPos
     * }
     */
    public static MemorySegment WorkPos(MemorySegment struct) {
        return struct.asSlice(WorkPos$OFFSET, WorkPos$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec2_c WorkPos
     * }
     */
    public static void WorkPos(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, WorkPos$OFFSET, WorkPos$LAYOUT.byteSize());
    }

    private static final GroupLayout WorkSize$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("WorkSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec2_c WorkSize
     * }
     */
    public static final GroupLayout WorkSize$layout() {
        return WorkSize$LAYOUT;
    }

    private static final long WorkSize$OFFSET = $LAYOUT.byteOffset(groupElement("WorkSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec2_c WorkSize
     * }
     */
    public static final long WorkSize$offset() {
        return WorkSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec2_c WorkSize
     * }
     */
    public static MemorySegment WorkSize(MemorySegment struct) {
        return struct.asSlice(WorkSize$OFFSET, WorkSize$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec2_c WorkSize
     * }
     */
    public static void WorkSize(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, WorkSize$OFFSET, WorkSize$LAYOUT.byteSize());
    }

    private static final AddressLayout PlatformHandle$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("PlatformHandle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *PlatformHandle
     * }
     */
    public static final AddressLayout PlatformHandle$layout() {
        return PlatformHandle$LAYOUT;
    }

    private static final long PlatformHandle$OFFSET = $LAYOUT.byteOffset(groupElement("PlatformHandle"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *PlatformHandle
     * }
     */
    public static final long PlatformHandle$offset() {
        return PlatformHandle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *PlatformHandle
     * }
     */
    public static MemorySegment PlatformHandle(MemorySegment struct) {
        return struct.get(PlatformHandle$LAYOUT, PlatformHandle$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *PlatformHandle
     * }
     */
    public static void PlatformHandle(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(PlatformHandle$LAYOUT, PlatformHandle$OFFSET, fieldValue);
    }

    private static final AddressLayout PlatformHandleRaw$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("PlatformHandleRaw"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *PlatformHandleRaw
     * }
     */
    public static final AddressLayout PlatformHandleRaw$layout() {
        return PlatformHandleRaw$LAYOUT;
    }

    private static final long PlatformHandleRaw$OFFSET = $LAYOUT.byteOffset(groupElement("PlatformHandleRaw"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *PlatformHandleRaw
     * }
     */
    public static final long PlatformHandleRaw$offset() {
        return PlatformHandleRaw$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *PlatformHandleRaw
     * }
     */
    public static MemorySegment PlatformHandleRaw(MemorySegment struct) {
        return struct.get(PlatformHandleRaw$LAYOUT, PlatformHandleRaw$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *PlatformHandleRaw
     * }
     */
    public static void PlatformHandleRaw(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(PlatformHandleRaw$LAYOUT, PlatformHandleRaw$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

