// Generated by jextract

package net.bplo.libs.jimgui.binding;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ImGuiTreeNodeStackData {
 *     ImGuiID ID;
 *     ImGuiTreeNodeFlags TreeFlags;
 *     ImGuiItemFlags ItemFlags;
 *     ImRect_c NavRect;
 *     float DrawLinesX1;
 *     float DrawLinesToNodesY2;
 *     ImGuiTableColumnIdx DrawLinesTableColumn;
 * }
 * }
 */
public class ImGuiTreeNodeStackData {

    ImGuiTreeNodeStackData() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        cimgui_h.C_INT.withName("ID"),
        cimgui_h.C_INT.withName("TreeFlags"),
        cimgui_h.C_INT.withName("ItemFlags"),
        ImRect_c.layout().withName("NavRect"),
        cimgui_h.C_FLOAT.withName("DrawLinesX1"),
        cimgui_h.C_FLOAT.withName("DrawLinesToNodesY2"),
        cimgui_h.C_SHORT.withName("DrawLinesTableColumn"),
        MemoryLayout.paddingLayout(2)
    ).withName("ImGuiTreeNodeStackData");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt ID$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ID"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImGuiID ID
     * }
     */
    public static final OfInt ID$layout() {
        return ID$LAYOUT;
    }

    private static final long ID$OFFSET = $LAYOUT.byteOffset(groupElement("ID"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImGuiID ID
     * }
     */
    public static final long ID$offset() {
        return ID$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImGuiID ID
     * }
     */
    public static int ID(MemorySegment struct) {
        return struct.get(ID$LAYOUT, ID$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImGuiID ID
     * }
     */
    public static void ID(MemorySegment struct, int fieldValue) {
        struct.set(ID$LAYOUT, ID$OFFSET, fieldValue);
    }

    private static final OfInt TreeFlags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("TreeFlags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImGuiTreeNodeFlags TreeFlags
     * }
     */
    public static final OfInt TreeFlags$layout() {
        return TreeFlags$LAYOUT;
    }

    private static final long TreeFlags$OFFSET = $LAYOUT.byteOffset(groupElement("TreeFlags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImGuiTreeNodeFlags TreeFlags
     * }
     */
    public static final long TreeFlags$offset() {
        return TreeFlags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImGuiTreeNodeFlags TreeFlags
     * }
     */
    public static int TreeFlags(MemorySegment struct) {
        return struct.get(TreeFlags$LAYOUT, TreeFlags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImGuiTreeNodeFlags TreeFlags
     * }
     */
    public static void TreeFlags(MemorySegment struct, int fieldValue) {
        struct.set(TreeFlags$LAYOUT, TreeFlags$OFFSET, fieldValue);
    }

    private static final OfInt ItemFlags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ItemFlags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImGuiItemFlags ItemFlags
     * }
     */
    public static final OfInt ItemFlags$layout() {
        return ItemFlags$LAYOUT;
    }

    private static final long ItemFlags$OFFSET = $LAYOUT.byteOffset(groupElement("ItemFlags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImGuiItemFlags ItemFlags
     * }
     */
    public static final long ItemFlags$offset() {
        return ItemFlags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImGuiItemFlags ItemFlags
     * }
     */
    public static int ItemFlags(MemorySegment struct) {
        return struct.get(ItemFlags$LAYOUT, ItemFlags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImGuiItemFlags ItemFlags
     * }
     */
    public static void ItemFlags(MemorySegment struct, int fieldValue) {
        struct.set(ItemFlags$LAYOUT, ItemFlags$OFFSET, fieldValue);
    }

    private static final GroupLayout NavRect$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("NavRect"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImRect_c NavRect
     * }
     */
    public static final GroupLayout NavRect$layout() {
        return NavRect$LAYOUT;
    }

    private static final long NavRect$OFFSET = $LAYOUT.byteOffset(groupElement("NavRect"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImRect_c NavRect
     * }
     */
    public static final long NavRect$offset() {
        return NavRect$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImRect_c NavRect
     * }
     */
    public static MemorySegment NavRect(MemorySegment struct) {
        return struct.asSlice(NavRect$OFFSET, NavRect$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImRect_c NavRect
     * }
     */
    public static void NavRect(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, NavRect$OFFSET, NavRect$LAYOUT.byteSize());
    }

    private static final OfFloat DrawLinesX1$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("DrawLinesX1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float DrawLinesX1
     * }
     */
    public static final OfFloat DrawLinesX1$layout() {
        return DrawLinesX1$LAYOUT;
    }

    private static final long DrawLinesX1$OFFSET = $LAYOUT.byteOffset(groupElement("DrawLinesX1"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float DrawLinesX1
     * }
     */
    public static final long DrawLinesX1$offset() {
        return DrawLinesX1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float DrawLinesX1
     * }
     */
    public static float DrawLinesX1(MemorySegment struct) {
        return struct.get(DrawLinesX1$LAYOUT, DrawLinesX1$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float DrawLinesX1
     * }
     */
    public static void DrawLinesX1(MemorySegment struct, float fieldValue) {
        struct.set(DrawLinesX1$LAYOUT, DrawLinesX1$OFFSET, fieldValue);
    }

    private static final OfFloat DrawLinesToNodesY2$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("DrawLinesToNodesY2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float DrawLinesToNodesY2
     * }
     */
    public static final OfFloat DrawLinesToNodesY2$layout() {
        return DrawLinesToNodesY2$LAYOUT;
    }

    private static final long DrawLinesToNodesY2$OFFSET = $LAYOUT.byteOffset(groupElement("DrawLinesToNodesY2"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float DrawLinesToNodesY2
     * }
     */
    public static final long DrawLinesToNodesY2$offset() {
        return DrawLinesToNodesY2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float DrawLinesToNodesY2
     * }
     */
    public static float DrawLinesToNodesY2(MemorySegment struct) {
        return struct.get(DrawLinesToNodesY2$LAYOUT, DrawLinesToNodesY2$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float DrawLinesToNodesY2
     * }
     */
    public static void DrawLinesToNodesY2(MemorySegment struct, float fieldValue) {
        struct.set(DrawLinesToNodesY2$LAYOUT, DrawLinesToNodesY2$OFFSET, fieldValue);
    }

    private static final OfShort DrawLinesTableColumn$LAYOUT = (OfShort)$LAYOUT.select(groupElement("DrawLinesTableColumn"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImGuiTableColumnIdx DrawLinesTableColumn
     * }
     */
    public static final OfShort DrawLinesTableColumn$layout() {
        return DrawLinesTableColumn$LAYOUT;
    }

    private static final long DrawLinesTableColumn$OFFSET = $LAYOUT.byteOffset(groupElement("DrawLinesTableColumn"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImGuiTableColumnIdx DrawLinesTableColumn
     * }
     */
    public static final long DrawLinesTableColumn$offset() {
        return DrawLinesTableColumn$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImGuiTableColumnIdx DrawLinesTableColumn
     * }
     */
    public static short DrawLinesTableColumn(MemorySegment struct) {
        return struct.get(DrawLinesTableColumn$LAYOUT, DrawLinesTableColumn$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImGuiTableColumnIdx DrawLinesTableColumn
     * }
     */
    public static void DrawLinesTableColumn(MemorySegment struct, short fieldValue) {
        struct.set(DrawLinesTableColumn$LAYOUT, DrawLinesTableColumn$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

