// Generated by jextract

package test;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class test_bool_h extends test_bool_h$shared {

    test_bool_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.libraryLookup(System.mapLibraryName("test"), LIBRARY_ARENA)
            .or(SymbolLookup.loaderLookup())
            .or(Linker.nativeLinker().defaultLookup());

    private static final int true_ = (int)1L;
    /**
     * {@snippet lang=c :
     * #define true 1
     * }
     */
    public static int true_() {
        return true_;
    }
    private static final int false_ = (int)0L;
    /**
     * {@snippet lang=c :
     * #define false 0
     * }
     */
    public static int false_() {
        return false_;
    }
    private static final int __bool_true_false_are_defined = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __bool_true_false_are_defined 1
     * }
     */
    public static int __bool_true_false_are_defined() {
        return __bool_true_false_are_defined;
    }

    private static class test_func {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            test_bool_h.C_BOOL,
            test_bool_h.C_POINTER,
            test_bool_h.C_POINTER,
            test_bool_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("test_func");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern _Bool test_func(const char *name, _Bool *p_open, int flags)
     * }
     */
    public static FunctionDescriptor test_func$descriptor() {
        return test_func.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern _Bool test_func(const char *name, _Bool *p_open, int flags)
     * }
     */
    public static MethodHandle test_func$handle() {
        return test_func.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern _Bool test_func(const char *name, _Bool *p_open, int flags)
     * }
     */
    public static MemorySegment test_func$address() {
        return test_func.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern _Bool test_func(const char *name, _Bool *p_open, int flags)
     * }
     */
    public static boolean test_func(MemorySegment name, MemorySegment p_open, int flags) {
        var mh$ = test_func.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("test_func", name, p_open, flags);
            }
            return (boolean)mh$.invokeExact(name, p_open, flags);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class test_func2 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            test_bool_h.C_BOOL,
            test_bool_h.C_POINTER,
            test_bool_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("test_func2");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern _Bool test_func2(const char *name, int flags)
     * }
     */
    public static FunctionDescriptor test_func2$descriptor() {
        return test_func2.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern _Bool test_func2(const char *name, int flags)
     * }
     */
    public static MethodHandle test_func2$handle() {
        return test_func2.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern _Bool test_func2(const char *name, int flags)
     * }
     */
    public static MemorySegment test_func2$address() {
        return test_func2.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern _Bool test_func2(const char *name, int flags)
     * }
     */
    public static boolean test_func2(MemorySegment name, int flags) {
        var mh$ = test_func2.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("test_func2", name, flags);
            }
            return (boolean)mh$.invokeExact(name, flags);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

