// Generated by jextract

package net.bplo.libs.jimgui.binding;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ImDrawCmdHeader {
 *     ImVec4_c ClipRect;
 *     ImTextureRef_c TexRef;
 *     unsigned int VtxOffset;
 * }
 * }
 */
public class ImDrawCmdHeader {

    ImDrawCmdHeader() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ImVec4_c.layout().withName("ClipRect"),
        ImTextureRef_c.layout().withName("TexRef"),
        cimgui_h.C_INT.withName("VtxOffset"),
        MemoryLayout.paddingLayout(4)
    ).withName("ImDrawCmdHeader");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout ClipRect$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("ClipRect"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec4_c ClipRect
     * }
     */
    public static final GroupLayout ClipRect$layout() {
        return ClipRect$LAYOUT;
    }

    private static final long ClipRect$OFFSET = $LAYOUT.byteOffset(groupElement("ClipRect"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec4_c ClipRect
     * }
     */
    public static final long ClipRect$offset() {
        return ClipRect$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec4_c ClipRect
     * }
     */
    public static MemorySegment ClipRect(MemorySegment struct) {
        return struct.asSlice(ClipRect$OFFSET, ClipRect$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec4_c ClipRect
     * }
     */
    public static void ClipRect(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ClipRect$OFFSET, ClipRect$LAYOUT.byteSize());
    }

    private static final GroupLayout TexRef$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("TexRef"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImTextureRef_c TexRef
     * }
     */
    public static final GroupLayout TexRef$layout() {
        return TexRef$LAYOUT;
    }

    private static final long TexRef$OFFSET = $LAYOUT.byteOffset(groupElement("TexRef"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImTextureRef_c TexRef
     * }
     */
    public static final long TexRef$offset() {
        return TexRef$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImTextureRef_c TexRef
     * }
     */
    public static MemorySegment TexRef(MemorySegment struct) {
        return struct.asSlice(TexRef$OFFSET, TexRef$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImTextureRef_c TexRef
     * }
     */
    public static void TexRef(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, TexRef$OFFSET, TexRef$LAYOUT.byteSize());
    }

    private static final OfInt VtxOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("VtxOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int VtxOffset
     * }
     */
    public static final OfInt VtxOffset$layout() {
        return VtxOffset$LAYOUT;
    }

    private static final long VtxOffset$OFFSET = $LAYOUT.byteOffset(groupElement("VtxOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int VtxOffset
     * }
     */
    public static final long VtxOffset$offset() {
        return VtxOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int VtxOffset
     * }
     */
    public static int VtxOffset(MemorySegment struct) {
        return struct.get(VtxOffset$LAYOUT, VtxOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int VtxOffset
     * }
     */
    public static void VtxOffset(MemorySegment struct, int fieldValue) {
        struct.set(VtxOffset$LAYOUT, VtxOffset$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

