// Generated by jextract

package net.bplo.libs.jimgui.binding;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ImFontBaked {
 *     ImVector_float IndexAdvanceX;
 *     float FallbackAdvanceX;
 *     float Size;
 *     float RasterizerDensity;
 *     ImVector_ImU16 IndexLookup;
 *     ImVector_ImFontGlyph Glyphs;
 *     int FallbackGlyphIndex;
 *     float Ascent;
 *     float Descent;
 *     unsigned int MetricsTotalSurface : 26;
 *     unsigned int WantDestroy : 1;
 *     unsigned int LoadNoFallback : 1;
 *     unsigned int LoadNoRenderOnLayout : 1;
 *     int LastUsedFrame;
 *     ImGuiID BakedId;
 *     ImFont *OwnerFont;
 *     void *FontLoaderDatas;
 * }
 * }
 */
public class ImFontBaked {

    ImFontBaked() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ImVector_float.layout().withName("IndexAdvanceX"),
        cimgui_h.C_FLOAT.withName("FallbackAdvanceX"),
        cimgui_h.C_FLOAT.withName("Size"),
        cimgui_h.C_FLOAT.withName("RasterizerDensity"),
        MemoryLayout.paddingLayout(4),
        ImVector_ImU16.layout().withName("IndexLookup"),
        ImVector_ImFontGlyph.layout().withName("Glyphs"),
        cimgui_h.C_INT.withName("FallbackGlyphIndex"),
        cimgui_h.C_FLOAT.withName("Ascent"),
        cimgui_h.C_FLOAT.withName("Descent"),
        MemoryLayout.paddingLayout(4),
        cimgui_h.C_INT.withName("LastUsedFrame"),
        cimgui_h.C_INT.withName("BakedId"),
        cimgui_h.C_POINTER.withName("OwnerFont"),
        cimgui_h.C_POINTER.withName("FontLoaderDatas")
    ).withName("ImFontBaked");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout IndexAdvanceX$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("IndexAdvanceX"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVector_float IndexAdvanceX
     * }
     */
    public static final GroupLayout IndexAdvanceX$layout() {
        return IndexAdvanceX$LAYOUT;
    }

    private static final long IndexAdvanceX$OFFSET = $LAYOUT.byteOffset(groupElement("IndexAdvanceX"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVector_float IndexAdvanceX
     * }
     */
    public static final long IndexAdvanceX$offset() {
        return IndexAdvanceX$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVector_float IndexAdvanceX
     * }
     */
    public static MemorySegment IndexAdvanceX(MemorySegment struct) {
        return struct.asSlice(IndexAdvanceX$OFFSET, IndexAdvanceX$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVector_float IndexAdvanceX
     * }
     */
    public static void IndexAdvanceX(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, IndexAdvanceX$OFFSET, IndexAdvanceX$LAYOUT.byteSize());
    }

    private static final OfFloat FallbackAdvanceX$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("FallbackAdvanceX"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float FallbackAdvanceX
     * }
     */
    public static final OfFloat FallbackAdvanceX$layout() {
        return FallbackAdvanceX$LAYOUT;
    }

    private static final long FallbackAdvanceX$OFFSET = $LAYOUT.byteOffset(groupElement("FallbackAdvanceX"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float FallbackAdvanceX
     * }
     */
    public static final long FallbackAdvanceX$offset() {
        return FallbackAdvanceX$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float FallbackAdvanceX
     * }
     */
    public static float FallbackAdvanceX(MemorySegment struct) {
        return struct.get(FallbackAdvanceX$LAYOUT, FallbackAdvanceX$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float FallbackAdvanceX
     * }
     */
    public static void FallbackAdvanceX(MemorySegment struct, float fieldValue) {
        struct.set(FallbackAdvanceX$LAYOUT, FallbackAdvanceX$OFFSET, fieldValue);
    }

    private static final OfFloat Size$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("Size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float Size
     * }
     */
    public static final OfFloat Size$layout() {
        return Size$LAYOUT;
    }

    private static final long Size$OFFSET = $LAYOUT.byteOffset(groupElement("Size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float Size
     * }
     */
    public static final long Size$offset() {
        return Size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float Size
     * }
     */
    public static float Size(MemorySegment struct) {
        return struct.get(Size$LAYOUT, Size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float Size
     * }
     */
    public static void Size(MemorySegment struct, float fieldValue) {
        struct.set(Size$LAYOUT, Size$OFFSET, fieldValue);
    }

    private static final OfFloat RasterizerDensity$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("RasterizerDensity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float RasterizerDensity
     * }
     */
    public static final OfFloat RasterizerDensity$layout() {
        return RasterizerDensity$LAYOUT;
    }

    private static final long RasterizerDensity$OFFSET = $LAYOUT.byteOffset(groupElement("RasterizerDensity"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float RasterizerDensity
     * }
     */
    public static final long RasterizerDensity$offset() {
        return RasterizerDensity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float RasterizerDensity
     * }
     */
    public static float RasterizerDensity(MemorySegment struct) {
        return struct.get(RasterizerDensity$LAYOUT, RasterizerDensity$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float RasterizerDensity
     * }
     */
    public static void RasterizerDensity(MemorySegment struct, float fieldValue) {
        struct.set(RasterizerDensity$LAYOUT, RasterizerDensity$OFFSET, fieldValue);
    }

    private static final GroupLayout IndexLookup$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("IndexLookup"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVector_ImU16 IndexLookup
     * }
     */
    public static final GroupLayout IndexLookup$layout() {
        return IndexLookup$LAYOUT;
    }

    private static final long IndexLookup$OFFSET = $LAYOUT.byteOffset(groupElement("IndexLookup"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVector_ImU16 IndexLookup
     * }
     */
    public static final long IndexLookup$offset() {
        return IndexLookup$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVector_ImU16 IndexLookup
     * }
     */
    public static MemorySegment IndexLookup(MemorySegment struct) {
        return struct.asSlice(IndexLookup$OFFSET, IndexLookup$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVector_ImU16 IndexLookup
     * }
     */
    public static void IndexLookup(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, IndexLookup$OFFSET, IndexLookup$LAYOUT.byteSize());
    }

    private static final GroupLayout Glyphs$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("Glyphs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVector_ImFontGlyph Glyphs
     * }
     */
    public static final GroupLayout Glyphs$layout() {
        return Glyphs$LAYOUT;
    }

    private static final long Glyphs$OFFSET = $LAYOUT.byteOffset(groupElement("Glyphs"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVector_ImFontGlyph Glyphs
     * }
     */
    public static final long Glyphs$offset() {
        return Glyphs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVector_ImFontGlyph Glyphs
     * }
     */
    public static MemorySegment Glyphs(MemorySegment struct) {
        return struct.asSlice(Glyphs$OFFSET, Glyphs$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVector_ImFontGlyph Glyphs
     * }
     */
    public static void Glyphs(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, Glyphs$OFFSET, Glyphs$LAYOUT.byteSize());
    }

    private static final OfInt FallbackGlyphIndex$LAYOUT = (OfInt)$LAYOUT.select(groupElement("FallbackGlyphIndex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int FallbackGlyphIndex
     * }
     */
    public static final OfInt FallbackGlyphIndex$layout() {
        return FallbackGlyphIndex$LAYOUT;
    }

    private static final long FallbackGlyphIndex$OFFSET = $LAYOUT.byteOffset(groupElement("FallbackGlyphIndex"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int FallbackGlyphIndex
     * }
     */
    public static final long FallbackGlyphIndex$offset() {
        return FallbackGlyphIndex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int FallbackGlyphIndex
     * }
     */
    public static int FallbackGlyphIndex(MemorySegment struct) {
        return struct.get(FallbackGlyphIndex$LAYOUT, FallbackGlyphIndex$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int FallbackGlyphIndex
     * }
     */
    public static void FallbackGlyphIndex(MemorySegment struct, int fieldValue) {
        struct.set(FallbackGlyphIndex$LAYOUT, FallbackGlyphIndex$OFFSET, fieldValue);
    }

    private static final OfFloat Ascent$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("Ascent"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float Ascent
     * }
     */
    public static final OfFloat Ascent$layout() {
        return Ascent$LAYOUT;
    }

    private static final long Ascent$OFFSET = $LAYOUT.byteOffset(groupElement("Ascent"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float Ascent
     * }
     */
    public static final long Ascent$offset() {
        return Ascent$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float Ascent
     * }
     */
    public static float Ascent(MemorySegment struct) {
        return struct.get(Ascent$LAYOUT, Ascent$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float Ascent
     * }
     */
    public static void Ascent(MemorySegment struct, float fieldValue) {
        struct.set(Ascent$LAYOUT, Ascent$OFFSET, fieldValue);
    }

    private static final OfFloat Descent$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("Descent"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float Descent
     * }
     */
    public static final OfFloat Descent$layout() {
        return Descent$LAYOUT;
    }

    private static final long Descent$OFFSET = $LAYOUT.byteOffset(groupElement("Descent"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float Descent
     * }
     */
    public static final long Descent$offset() {
        return Descent$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float Descent
     * }
     */
    public static float Descent(MemorySegment struct) {
        return struct.get(Descent$LAYOUT, Descent$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float Descent
     * }
     */
    public static void Descent(MemorySegment struct, float fieldValue) {
        struct.set(Descent$LAYOUT, Descent$OFFSET, fieldValue);
    }

    private static final OfInt LastUsedFrame$LAYOUT = (OfInt)$LAYOUT.select(groupElement("LastUsedFrame"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int LastUsedFrame
     * }
     */
    public static final OfInt LastUsedFrame$layout() {
        return LastUsedFrame$LAYOUT;
    }

    private static final long LastUsedFrame$OFFSET = $LAYOUT.byteOffset(groupElement("LastUsedFrame"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int LastUsedFrame
     * }
     */
    public static final long LastUsedFrame$offset() {
        return LastUsedFrame$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int LastUsedFrame
     * }
     */
    public static int LastUsedFrame(MemorySegment struct) {
        return struct.get(LastUsedFrame$LAYOUT, LastUsedFrame$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int LastUsedFrame
     * }
     */
    public static void LastUsedFrame(MemorySegment struct, int fieldValue) {
        struct.set(LastUsedFrame$LAYOUT, LastUsedFrame$OFFSET, fieldValue);
    }

    private static final OfInt BakedId$LAYOUT = (OfInt)$LAYOUT.select(groupElement("BakedId"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImGuiID BakedId
     * }
     */
    public static final OfInt BakedId$layout() {
        return BakedId$LAYOUT;
    }

    private static final long BakedId$OFFSET = $LAYOUT.byteOffset(groupElement("BakedId"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImGuiID BakedId
     * }
     */
    public static final long BakedId$offset() {
        return BakedId$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImGuiID BakedId
     * }
     */
    public static int BakedId(MemorySegment struct) {
        return struct.get(BakedId$LAYOUT, BakedId$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImGuiID BakedId
     * }
     */
    public static void BakedId(MemorySegment struct, int fieldValue) {
        struct.set(BakedId$LAYOUT, BakedId$OFFSET, fieldValue);
    }

    private static final AddressLayout OwnerFont$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("OwnerFont"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImFont *OwnerFont
     * }
     */
    public static final AddressLayout OwnerFont$layout() {
        return OwnerFont$LAYOUT;
    }

    private static final long OwnerFont$OFFSET = $LAYOUT.byteOffset(groupElement("OwnerFont"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImFont *OwnerFont
     * }
     */
    public static final long OwnerFont$offset() {
        return OwnerFont$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImFont *OwnerFont
     * }
     */
    public static MemorySegment OwnerFont(MemorySegment struct) {
        return struct.get(OwnerFont$LAYOUT, OwnerFont$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImFont *OwnerFont
     * }
     */
    public static void OwnerFont(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(OwnerFont$LAYOUT, OwnerFont$OFFSET, fieldValue);
    }

    private static final AddressLayout FontLoaderDatas$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("FontLoaderDatas"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *FontLoaderDatas
     * }
     */
    public static final AddressLayout FontLoaderDatas$layout() {
        return FontLoaderDatas$LAYOUT;
    }

    private static final long FontLoaderDatas$OFFSET = $LAYOUT.byteOffset(groupElement("FontLoaderDatas"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *FontLoaderDatas
     * }
     */
    public static final long FontLoaderDatas$offset() {
        return FontLoaderDatas$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *FontLoaderDatas
     * }
     */
    public static MemorySegment FontLoaderDatas(MemorySegment struct) {
        return struct.get(FontLoaderDatas$LAYOUT, FontLoaderDatas$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *FontLoaderDatas
     * }
     */
    public static void FontLoaderDatas(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(FontLoaderDatas$LAYOUT, FontLoaderDatas$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

