// Generated by jextract

package net.bplo.libs.jimgui.binding;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ImFontLoader {
 *     const char *Name;
 *     bool (*LoaderInit)(ImFontAtlas *);
 *     void (*LoaderShutdown)(ImFontAtlas *);
 *     bool (*FontSrcInit)(ImFontAtlas *, ImFontConfig *);
 *     void (*FontSrcDestroy)(ImFontAtlas *, ImFontConfig *);
 *     bool (*FontSrcContainsGlyph)(ImFontAtlas *, ImFontConfig *, ImWchar);
 *     bool (*FontBakedInit)(ImFontAtlas *, ImFontConfig *, ImFontBaked *, void *);
 *     void (*FontBakedDestroy)(ImFontAtlas *, ImFontConfig *, ImFontBaked *, void *);
 *     bool (*FontBakedLoadGlyph)(ImFontAtlas *, ImFontConfig *, ImFontBaked *, void *, ImWchar, ImFontGlyph *, float *);
 *     size_t FontBakedSrcLoaderDataSize;
 * }
 * }
 */
public class ImFontLoader {

    ImFontLoader() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        cimgui_h.C_POINTER.withName("Name"),
        cimgui_h.C_POINTER.withName("LoaderInit"),
        cimgui_h.C_POINTER.withName("LoaderShutdown"),
        cimgui_h.C_POINTER.withName("FontSrcInit"),
        cimgui_h.C_POINTER.withName("FontSrcDestroy"),
        cimgui_h.C_POINTER.withName("FontSrcContainsGlyph"),
        cimgui_h.C_POINTER.withName("FontBakedInit"),
        cimgui_h.C_POINTER.withName("FontBakedDestroy"),
        cimgui_h.C_POINTER.withName("FontBakedLoadGlyph"),
        cimgui_h.C_LONG_LONG.withName("FontBakedSrcLoaderDataSize")
    ).withName("ImFontLoader");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout Name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("Name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *Name
     * }
     */
    public static final AddressLayout Name$layout() {
        return Name$LAYOUT;
    }

    private static final long Name$OFFSET = $LAYOUT.byteOffset(groupElement("Name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *Name
     * }
     */
    public static final long Name$offset() {
        return Name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *Name
     * }
     */
    public static MemorySegment Name(MemorySegment struct) {
        return struct.get(Name$LAYOUT, Name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *Name
     * }
     */
    public static void Name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(Name$LAYOUT, Name$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * bool (*LoaderInit)(ImFontAtlas *)
     * }
     */
    public final static class LoaderInit {

        private LoaderInit() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            boolean apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cimgui_h.C_BOOL,
            cimgui_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cimgui_h.upcallHandle(LoaderInit.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(LoaderInit.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static boolean invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (boolean) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout LoaderInit$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("LoaderInit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool (*LoaderInit)(ImFontAtlas *)
     * }
     */
    public static final AddressLayout LoaderInit$layout() {
        return LoaderInit$LAYOUT;
    }

    private static final long LoaderInit$OFFSET = $LAYOUT.byteOffset(groupElement("LoaderInit"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool (*LoaderInit)(ImFontAtlas *)
     * }
     */
    public static final long LoaderInit$offset() {
        return LoaderInit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool (*LoaderInit)(ImFontAtlas *)
     * }
     */
    public static MemorySegment LoaderInit(MemorySegment struct) {
        return struct.get(LoaderInit$LAYOUT, LoaderInit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool (*LoaderInit)(ImFontAtlas *)
     * }
     */
    public static void LoaderInit(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(LoaderInit$LAYOUT, LoaderInit$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*LoaderShutdown)(ImFontAtlas *)
     * }
     */
    public final static class LoaderShutdown {

        private LoaderShutdown() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            cimgui_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cimgui_h.upcallHandle(LoaderShutdown.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(LoaderShutdown.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout LoaderShutdown$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("LoaderShutdown"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*LoaderShutdown)(ImFontAtlas *)
     * }
     */
    public static final AddressLayout LoaderShutdown$layout() {
        return LoaderShutdown$LAYOUT;
    }

    private static final long LoaderShutdown$OFFSET = $LAYOUT.byteOffset(groupElement("LoaderShutdown"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*LoaderShutdown)(ImFontAtlas *)
     * }
     */
    public static final long LoaderShutdown$offset() {
        return LoaderShutdown$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*LoaderShutdown)(ImFontAtlas *)
     * }
     */
    public static MemorySegment LoaderShutdown(MemorySegment struct) {
        return struct.get(LoaderShutdown$LAYOUT, LoaderShutdown$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*LoaderShutdown)(ImFontAtlas *)
     * }
     */
    public static void LoaderShutdown(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(LoaderShutdown$LAYOUT, LoaderShutdown$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * bool (*FontSrcInit)(ImFontAtlas *, ImFontConfig *)
     * }
     */
    public final static class FontSrcInit {

        private FontSrcInit() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            boolean apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cimgui_h.C_BOOL,
            cimgui_h.C_POINTER,
            cimgui_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cimgui_h.upcallHandle(FontSrcInit.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(FontSrcInit.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static boolean invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                return (boolean) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout FontSrcInit$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("FontSrcInit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool (*FontSrcInit)(ImFontAtlas *, ImFontConfig *)
     * }
     */
    public static final AddressLayout FontSrcInit$layout() {
        return FontSrcInit$LAYOUT;
    }

    private static final long FontSrcInit$OFFSET = $LAYOUT.byteOffset(groupElement("FontSrcInit"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool (*FontSrcInit)(ImFontAtlas *, ImFontConfig *)
     * }
     */
    public static final long FontSrcInit$offset() {
        return FontSrcInit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool (*FontSrcInit)(ImFontAtlas *, ImFontConfig *)
     * }
     */
    public static MemorySegment FontSrcInit(MemorySegment struct) {
        return struct.get(FontSrcInit$LAYOUT, FontSrcInit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool (*FontSrcInit)(ImFontAtlas *, ImFontConfig *)
     * }
     */
    public static void FontSrcInit(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(FontSrcInit$LAYOUT, FontSrcInit$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*FontSrcDestroy)(ImFontAtlas *, ImFontConfig *)
     * }
     */
    public final static class FontSrcDestroy {

        private FontSrcDestroy() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            cimgui_h.C_POINTER,
            cimgui_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cimgui_h.upcallHandle(FontSrcDestroy.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(FontSrcDestroy.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout FontSrcDestroy$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("FontSrcDestroy"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*FontSrcDestroy)(ImFontAtlas *, ImFontConfig *)
     * }
     */
    public static final AddressLayout FontSrcDestroy$layout() {
        return FontSrcDestroy$LAYOUT;
    }

    private static final long FontSrcDestroy$OFFSET = $LAYOUT.byteOffset(groupElement("FontSrcDestroy"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*FontSrcDestroy)(ImFontAtlas *, ImFontConfig *)
     * }
     */
    public static final long FontSrcDestroy$offset() {
        return FontSrcDestroy$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*FontSrcDestroy)(ImFontAtlas *, ImFontConfig *)
     * }
     */
    public static MemorySegment FontSrcDestroy(MemorySegment struct) {
        return struct.get(FontSrcDestroy$LAYOUT, FontSrcDestroy$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*FontSrcDestroy)(ImFontAtlas *, ImFontConfig *)
     * }
     */
    public static void FontSrcDestroy(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(FontSrcDestroy$LAYOUT, FontSrcDestroy$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * bool (*FontSrcContainsGlyph)(ImFontAtlas *, ImFontConfig *, ImWchar)
     * }
     */
    public final static class FontSrcContainsGlyph {

        private FontSrcContainsGlyph() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            boolean apply(MemorySegment _x0, MemorySegment _x1, short _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cimgui_h.C_BOOL,
            cimgui_h.C_POINTER,
            cimgui_h.C_POINTER,
            cimgui_h.C_SHORT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cimgui_h.upcallHandle(FontSrcContainsGlyph.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(FontSrcContainsGlyph.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static boolean invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, short _x2) {
            try {
                return (boolean) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout FontSrcContainsGlyph$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("FontSrcContainsGlyph"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool (*FontSrcContainsGlyph)(ImFontAtlas *, ImFontConfig *, ImWchar)
     * }
     */
    public static final AddressLayout FontSrcContainsGlyph$layout() {
        return FontSrcContainsGlyph$LAYOUT;
    }

    private static final long FontSrcContainsGlyph$OFFSET = $LAYOUT.byteOffset(groupElement("FontSrcContainsGlyph"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool (*FontSrcContainsGlyph)(ImFontAtlas *, ImFontConfig *, ImWchar)
     * }
     */
    public static final long FontSrcContainsGlyph$offset() {
        return FontSrcContainsGlyph$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool (*FontSrcContainsGlyph)(ImFontAtlas *, ImFontConfig *, ImWchar)
     * }
     */
    public static MemorySegment FontSrcContainsGlyph(MemorySegment struct) {
        return struct.get(FontSrcContainsGlyph$LAYOUT, FontSrcContainsGlyph$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool (*FontSrcContainsGlyph)(ImFontAtlas *, ImFontConfig *, ImWchar)
     * }
     */
    public static void FontSrcContainsGlyph(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(FontSrcContainsGlyph$LAYOUT, FontSrcContainsGlyph$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * bool (*FontBakedInit)(ImFontAtlas *, ImFontConfig *, ImFontBaked *, void *)
     * }
     */
    public final static class FontBakedInit {

        private FontBakedInit() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            boolean apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cimgui_h.C_BOOL,
            cimgui_h.C_POINTER,
            cimgui_h.C_POINTER,
            cimgui_h.C_POINTER,
            cimgui_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cimgui_h.upcallHandle(FontBakedInit.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(FontBakedInit.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static boolean invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3) {
            try {
                return (boolean) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout FontBakedInit$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("FontBakedInit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool (*FontBakedInit)(ImFontAtlas *, ImFontConfig *, ImFontBaked *, void *)
     * }
     */
    public static final AddressLayout FontBakedInit$layout() {
        return FontBakedInit$LAYOUT;
    }

    private static final long FontBakedInit$OFFSET = $LAYOUT.byteOffset(groupElement("FontBakedInit"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool (*FontBakedInit)(ImFontAtlas *, ImFontConfig *, ImFontBaked *, void *)
     * }
     */
    public static final long FontBakedInit$offset() {
        return FontBakedInit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool (*FontBakedInit)(ImFontAtlas *, ImFontConfig *, ImFontBaked *, void *)
     * }
     */
    public static MemorySegment FontBakedInit(MemorySegment struct) {
        return struct.get(FontBakedInit$LAYOUT, FontBakedInit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool (*FontBakedInit)(ImFontAtlas *, ImFontConfig *, ImFontBaked *, void *)
     * }
     */
    public static void FontBakedInit(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(FontBakedInit$LAYOUT, FontBakedInit$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*FontBakedDestroy)(ImFontAtlas *, ImFontConfig *, ImFontBaked *, void *)
     * }
     */
    public final static class FontBakedDestroy {

        private FontBakedDestroy() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            cimgui_h.C_POINTER,
            cimgui_h.C_POINTER,
            cimgui_h.C_POINTER,
            cimgui_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cimgui_h.upcallHandle(FontBakedDestroy.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(FontBakedDestroy.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout FontBakedDestroy$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("FontBakedDestroy"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*FontBakedDestroy)(ImFontAtlas *, ImFontConfig *, ImFontBaked *, void *)
     * }
     */
    public static final AddressLayout FontBakedDestroy$layout() {
        return FontBakedDestroy$LAYOUT;
    }

    private static final long FontBakedDestroy$OFFSET = $LAYOUT.byteOffset(groupElement("FontBakedDestroy"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*FontBakedDestroy)(ImFontAtlas *, ImFontConfig *, ImFontBaked *, void *)
     * }
     */
    public static final long FontBakedDestroy$offset() {
        return FontBakedDestroy$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*FontBakedDestroy)(ImFontAtlas *, ImFontConfig *, ImFontBaked *, void *)
     * }
     */
    public static MemorySegment FontBakedDestroy(MemorySegment struct) {
        return struct.get(FontBakedDestroy$LAYOUT, FontBakedDestroy$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*FontBakedDestroy)(ImFontAtlas *, ImFontConfig *, ImFontBaked *, void *)
     * }
     */
    public static void FontBakedDestroy(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(FontBakedDestroy$LAYOUT, FontBakedDestroy$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * bool (*FontBakedLoadGlyph)(ImFontAtlas *, ImFontConfig *, ImFontBaked *, void *, ImWchar, ImFontGlyph *, float *)
     * }
     */
    public final static class FontBakedLoadGlyph {

        private FontBakedLoadGlyph() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            boolean apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3, short _x4, MemorySegment _x5, MemorySegment _x6);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            cimgui_h.C_BOOL,
            cimgui_h.C_POINTER,
            cimgui_h.C_POINTER,
            cimgui_h.C_POINTER,
            cimgui_h.C_POINTER,
            cimgui_h.C_SHORT,
            cimgui_h.C_POINTER,
            cimgui_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = cimgui_h.upcallHandle(FontBakedLoadGlyph.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(FontBakedLoadGlyph.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static boolean invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3, short _x4, MemorySegment _x5, MemorySegment _x6) {
            try {
                return (boolean) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4, _x5, _x6);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout FontBakedLoadGlyph$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("FontBakedLoadGlyph"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool (*FontBakedLoadGlyph)(ImFontAtlas *, ImFontConfig *, ImFontBaked *, void *, ImWchar, ImFontGlyph *, float *)
     * }
     */
    public static final AddressLayout FontBakedLoadGlyph$layout() {
        return FontBakedLoadGlyph$LAYOUT;
    }

    private static final long FontBakedLoadGlyph$OFFSET = $LAYOUT.byteOffset(groupElement("FontBakedLoadGlyph"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool (*FontBakedLoadGlyph)(ImFontAtlas *, ImFontConfig *, ImFontBaked *, void *, ImWchar, ImFontGlyph *, float *)
     * }
     */
    public static final long FontBakedLoadGlyph$offset() {
        return FontBakedLoadGlyph$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool (*FontBakedLoadGlyph)(ImFontAtlas *, ImFontConfig *, ImFontBaked *, void *, ImWchar, ImFontGlyph *, float *)
     * }
     */
    public static MemorySegment FontBakedLoadGlyph(MemorySegment struct) {
        return struct.get(FontBakedLoadGlyph$LAYOUT, FontBakedLoadGlyph$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool (*FontBakedLoadGlyph)(ImFontAtlas *, ImFontConfig *, ImFontBaked *, void *, ImWchar, ImFontGlyph *, float *)
     * }
     */
    public static void FontBakedLoadGlyph(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(FontBakedLoadGlyph$LAYOUT, FontBakedLoadGlyph$OFFSET, fieldValue);
    }

    private static final OfLong FontBakedSrcLoaderDataSize$LAYOUT = (OfLong)$LAYOUT.select(groupElement("FontBakedSrcLoaderDataSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t FontBakedSrcLoaderDataSize
     * }
     */
    public static final OfLong FontBakedSrcLoaderDataSize$layout() {
        return FontBakedSrcLoaderDataSize$LAYOUT;
    }

    private static final long FontBakedSrcLoaderDataSize$OFFSET = $LAYOUT.byteOffset(groupElement("FontBakedSrcLoaderDataSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t FontBakedSrcLoaderDataSize
     * }
     */
    public static final long FontBakedSrcLoaderDataSize$offset() {
        return FontBakedSrcLoaderDataSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t FontBakedSrcLoaderDataSize
     * }
     */
    public static long FontBakedSrcLoaderDataSize(MemorySegment struct) {
        return struct.get(FontBakedSrcLoaderDataSize$LAYOUT, FontBakedSrcLoaderDataSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t FontBakedSrcLoaderDataSize
     * }
     */
    public static void FontBakedSrcLoaderDataSize(MemorySegment struct, long fieldValue) {
        struct.set(FontBakedSrcLoaderDataSize$LAYOUT, FontBakedSrcLoaderDataSize$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

