// Generated by jextract

package net.bplo.libs.jimgui.binding;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ImFontConfig {
 *     char Name[40];
 *     void *FontData;
 *     int FontDataSize;
 *     bool FontDataOwnedByAtlas;
 *     bool MergeMode;
 *     bool PixelSnapH;
 *     ImS8 OversampleH;
 *     ImS8 OversampleV;
 *     ImWchar EllipsisChar;
 *     float SizePixels;
 *     const ImWchar *GlyphRanges;
 *     const ImWchar *GlyphExcludeRanges;
 *     ImVec2_c GlyphOffset;
 *     float GlyphMinAdvanceX;
 *     float GlyphMaxAdvanceX;
 *     float GlyphExtraAdvanceX;
 *     ImU32 FontNo;
 *     unsigned int FontLoaderFlags;
 *     float RasterizerMultiply;
 *     float RasterizerDensity;
 *     float ExtraSizeScale;
 *     ImFontFlags Flags;
 *     ImFont *DstFont;
 *     const ImFontLoader *FontLoader;
 *     void *FontLoaderData;
 * }
 * }
 */
public class ImFontConfig {

    ImFontConfig() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(40, cimgui_h.C_CHAR).withName("Name"),
        cimgui_h.C_POINTER.withName("FontData"),
        cimgui_h.C_INT.withName("FontDataSize"),
        cimgui_h.C_BOOL.withName("FontDataOwnedByAtlas"),
        cimgui_h.C_BOOL.withName("MergeMode"),
        cimgui_h.C_BOOL.withName("PixelSnapH"),
        cimgui_h.C_CHAR.withName("OversampleH"),
        cimgui_h.C_CHAR.withName("OversampleV"),
        MemoryLayout.paddingLayout(1),
        cimgui_h.C_SHORT.withName("EllipsisChar"),
        cimgui_h.C_FLOAT.withName("SizePixels"),
        cimgui_h.C_POINTER.withName("GlyphRanges"),
        cimgui_h.C_POINTER.withName("GlyphExcludeRanges"),
        ImVec2_c.layout().withName("GlyphOffset"),
        cimgui_h.C_FLOAT.withName("GlyphMinAdvanceX"),
        cimgui_h.C_FLOAT.withName("GlyphMaxAdvanceX"),
        cimgui_h.C_FLOAT.withName("GlyphExtraAdvanceX"),
        cimgui_h.C_INT.withName("FontNo"),
        cimgui_h.C_INT.withName("FontLoaderFlags"),
        cimgui_h.C_FLOAT.withName("RasterizerMultiply"),
        cimgui_h.C_FLOAT.withName("RasterizerDensity"),
        cimgui_h.C_FLOAT.withName("ExtraSizeScale"),
        cimgui_h.C_INT.withName("Flags"),
        MemoryLayout.paddingLayout(4),
        cimgui_h.C_POINTER.withName("DstFont"),
        cimgui_h.C_POINTER.withName("FontLoader"),
        cimgui_h.C_POINTER.withName("FontLoaderData")
    ).withName("ImFontConfig");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout Name$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("Name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char Name[40]
     * }
     */
    public static final SequenceLayout Name$layout() {
        return Name$LAYOUT;
    }

    private static final long Name$OFFSET = $LAYOUT.byteOffset(groupElement("Name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char Name[40]
     * }
     */
    public static final long Name$offset() {
        return Name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char Name[40]
     * }
     */
    public static MemorySegment Name(MemorySegment struct) {
        return struct.asSlice(Name$OFFSET, Name$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char Name[40]
     * }
     */
    public static void Name(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, Name$OFFSET, Name$LAYOUT.byteSize());
    }

    private static long[] Name$DIMS = { 40 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char Name[40]
     * }
     */
    public static long[] Name$dimensions() {
        return Name$DIMS;
    }
    private static final VarHandle Name$ELEM_HANDLE = Name$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char Name[40]
     * }
     */
    public static byte Name(MemorySegment struct, long index0) {
        return (byte)Name$ELEM_HANDLE.get(struct, Name$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char Name[40]
     * }
     */
    public static void Name(MemorySegment struct, long index0, byte fieldValue) {
        Name$ELEM_HANDLE.set(struct, Name$OFFSET, index0, fieldValue);
    }

    private static final AddressLayout FontData$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("FontData"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *FontData
     * }
     */
    public static final AddressLayout FontData$layout() {
        return FontData$LAYOUT;
    }

    private static final long FontData$OFFSET = $LAYOUT.byteOffset(groupElement("FontData"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *FontData
     * }
     */
    public static final long FontData$offset() {
        return FontData$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *FontData
     * }
     */
    public static MemorySegment FontData(MemorySegment struct) {
        return struct.get(FontData$LAYOUT, FontData$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *FontData
     * }
     */
    public static void FontData(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(FontData$LAYOUT, FontData$OFFSET, fieldValue);
    }

    private static final OfInt FontDataSize$LAYOUT = (OfInt)$LAYOUT.select(groupElement("FontDataSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int FontDataSize
     * }
     */
    public static final OfInt FontDataSize$layout() {
        return FontDataSize$LAYOUT;
    }

    private static final long FontDataSize$OFFSET = $LAYOUT.byteOffset(groupElement("FontDataSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int FontDataSize
     * }
     */
    public static final long FontDataSize$offset() {
        return FontDataSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int FontDataSize
     * }
     */
    public static int FontDataSize(MemorySegment struct) {
        return struct.get(FontDataSize$LAYOUT, FontDataSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int FontDataSize
     * }
     */
    public static void FontDataSize(MemorySegment struct, int fieldValue) {
        struct.set(FontDataSize$LAYOUT, FontDataSize$OFFSET, fieldValue);
    }

    private static final OfBoolean FontDataOwnedByAtlas$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("FontDataOwnedByAtlas"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool FontDataOwnedByAtlas
     * }
     */
    public static final OfBoolean FontDataOwnedByAtlas$layout() {
        return FontDataOwnedByAtlas$LAYOUT;
    }

    private static final long FontDataOwnedByAtlas$OFFSET = $LAYOUT.byteOffset(groupElement("FontDataOwnedByAtlas"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool FontDataOwnedByAtlas
     * }
     */
    public static final long FontDataOwnedByAtlas$offset() {
        return FontDataOwnedByAtlas$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool FontDataOwnedByAtlas
     * }
     */
    public static boolean FontDataOwnedByAtlas(MemorySegment struct) {
        return struct.get(FontDataOwnedByAtlas$LAYOUT, FontDataOwnedByAtlas$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool FontDataOwnedByAtlas
     * }
     */
    public static void FontDataOwnedByAtlas(MemorySegment struct, boolean fieldValue) {
        struct.set(FontDataOwnedByAtlas$LAYOUT, FontDataOwnedByAtlas$OFFSET, fieldValue);
    }

    private static final OfBoolean MergeMode$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("MergeMode"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool MergeMode
     * }
     */
    public static final OfBoolean MergeMode$layout() {
        return MergeMode$LAYOUT;
    }

    private static final long MergeMode$OFFSET = $LAYOUT.byteOffset(groupElement("MergeMode"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool MergeMode
     * }
     */
    public static final long MergeMode$offset() {
        return MergeMode$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool MergeMode
     * }
     */
    public static boolean MergeMode(MemorySegment struct) {
        return struct.get(MergeMode$LAYOUT, MergeMode$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool MergeMode
     * }
     */
    public static void MergeMode(MemorySegment struct, boolean fieldValue) {
        struct.set(MergeMode$LAYOUT, MergeMode$OFFSET, fieldValue);
    }

    private static final OfBoolean PixelSnapH$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("PixelSnapH"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool PixelSnapH
     * }
     */
    public static final OfBoolean PixelSnapH$layout() {
        return PixelSnapH$LAYOUT;
    }

    private static final long PixelSnapH$OFFSET = $LAYOUT.byteOffset(groupElement("PixelSnapH"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool PixelSnapH
     * }
     */
    public static final long PixelSnapH$offset() {
        return PixelSnapH$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool PixelSnapH
     * }
     */
    public static boolean PixelSnapH(MemorySegment struct) {
        return struct.get(PixelSnapH$LAYOUT, PixelSnapH$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool PixelSnapH
     * }
     */
    public static void PixelSnapH(MemorySegment struct, boolean fieldValue) {
        struct.set(PixelSnapH$LAYOUT, PixelSnapH$OFFSET, fieldValue);
    }

    private static final OfByte OversampleH$LAYOUT = (OfByte)$LAYOUT.select(groupElement("OversampleH"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImS8 OversampleH
     * }
     */
    public static final OfByte OversampleH$layout() {
        return OversampleH$LAYOUT;
    }

    private static final long OversampleH$OFFSET = $LAYOUT.byteOffset(groupElement("OversampleH"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImS8 OversampleH
     * }
     */
    public static final long OversampleH$offset() {
        return OversampleH$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImS8 OversampleH
     * }
     */
    public static byte OversampleH(MemorySegment struct) {
        return struct.get(OversampleH$LAYOUT, OversampleH$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImS8 OversampleH
     * }
     */
    public static void OversampleH(MemorySegment struct, byte fieldValue) {
        struct.set(OversampleH$LAYOUT, OversampleH$OFFSET, fieldValue);
    }

    private static final OfByte OversampleV$LAYOUT = (OfByte)$LAYOUT.select(groupElement("OversampleV"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImS8 OversampleV
     * }
     */
    public static final OfByte OversampleV$layout() {
        return OversampleV$LAYOUT;
    }

    private static final long OversampleV$OFFSET = $LAYOUT.byteOffset(groupElement("OversampleV"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImS8 OversampleV
     * }
     */
    public static final long OversampleV$offset() {
        return OversampleV$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImS8 OversampleV
     * }
     */
    public static byte OversampleV(MemorySegment struct) {
        return struct.get(OversampleV$LAYOUT, OversampleV$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImS8 OversampleV
     * }
     */
    public static void OversampleV(MemorySegment struct, byte fieldValue) {
        struct.set(OversampleV$LAYOUT, OversampleV$OFFSET, fieldValue);
    }

    private static final OfShort EllipsisChar$LAYOUT = (OfShort)$LAYOUT.select(groupElement("EllipsisChar"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImWchar EllipsisChar
     * }
     */
    public static final OfShort EllipsisChar$layout() {
        return EllipsisChar$LAYOUT;
    }

    private static final long EllipsisChar$OFFSET = $LAYOUT.byteOffset(groupElement("EllipsisChar"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImWchar EllipsisChar
     * }
     */
    public static final long EllipsisChar$offset() {
        return EllipsisChar$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImWchar EllipsisChar
     * }
     */
    public static short EllipsisChar(MemorySegment struct) {
        return struct.get(EllipsisChar$LAYOUT, EllipsisChar$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImWchar EllipsisChar
     * }
     */
    public static void EllipsisChar(MemorySegment struct, short fieldValue) {
        struct.set(EllipsisChar$LAYOUT, EllipsisChar$OFFSET, fieldValue);
    }

    private static final OfFloat SizePixels$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("SizePixels"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float SizePixels
     * }
     */
    public static final OfFloat SizePixels$layout() {
        return SizePixels$LAYOUT;
    }

    private static final long SizePixels$OFFSET = $LAYOUT.byteOffset(groupElement("SizePixels"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float SizePixels
     * }
     */
    public static final long SizePixels$offset() {
        return SizePixels$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float SizePixels
     * }
     */
    public static float SizePixels(MemorySegment struct) {
        return struct.get(SizePixels$LAYOUT, SizePixels$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float SizePixels
     * }
     */
    public static void SizePixels(MemorySegment struct, float fieldValue) {
        struct.set(SizePixels$LAYOUT, SizePixels$OFFSET, fieldValue);
    }

    private static final AddressLayout GlyphRanges$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("GlyphRanges"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const ImWchar *GlyphRanges
     * }
     */
    public static final AddressLayout GlyphRanges$layout() {
        return GlyphRanges$LAYOUT;
    }

    private static final long GlyphRanges$OFFSET = $LAYOUT.byteOffset(groupElement("GlyphRanges"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const ImWchar *GlyphRanges
     * }
     */
    public static final long GlyphRanges$offset() {
        return GlyphRanges$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const ImWchar *GlyphRanges
     * }
     */
    public static MemorySegment GlyphRanges(MemorySegment struct) {
        return struct.get(GlyphRanges$LAYOUT, GlyphRanges$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const ImWchar *GlyphRanges
     * }
     */
    public static void GlyphRanges(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(GlyphRanges$LAYOUT, GlyphRanges$OFFSET, fieldValue);
    }

    private static final AddressLayout GlyphExcludeRanges$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("GlyphExcludeRanges"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const ImWchar *GlyphExcludeRanges
     * }
     */
    public static final AddressLayout GlyphExcludeRanges$layout() {
        return GlyphExcludeRanges$LAYOUT;
    }

    private static final long GlyphExcludeRanges$OFFSET = $LAYOUT.byteOffset(groupElement("GlyphExcludeRanges"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const ImWchar *GlyphExcludeRanges
     * }
     */
    public static final long GlyphExcludeRanges$offset() {
        return GlyphExcludeRanges$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const ImWchar *GlyphExcludeRanges
     * }
     */
    public static MemorySegment GlyphExcludeRanges(MemorySegment struct) {
        return struct.get(GlyphExcludeRanges$LAYOUT, GlyphExcludeRanges$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const ImWchar *GlyphExcludeRanges
     * }
     */
    public static void GlyphExcludeRanges(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(GlyphExcludeRanges$LAYOUT, GlyphExcludeRanges$OFFSET, fieldValue);
    }

    private static final GroupLayout GlyphOffset$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("GlyphOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec2_c GlyphOffset
     * }
     */
    public static final GroupLayout GlyphOffset$layout() {
        return GlyphOffset$LAYOUT;
    }

    private static final long GlyphOffset$OFFSET = $LAYOUT.byteOffset(groupElement("GlyphOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec2_c GlyphOffset
     * }
     */
    public static final long GlyphOffset$offset() {
        return GlyphOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec2_c GlyphOffset
     * }
     */
    public static MemorySegment GlyphOffset(MemorySegment struct) {
        return struct.asSlice(GlyphOffset$OFFSET, GlyphOffset$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec2_c GlyphOffset
     * }
     */
    public static void GlyphOffset(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, GlyphOffset$OFFSET, GlyphOffset$LAYOUT.byteSize());
    }

    private static final OfFloat GlyphMinAdvanceX$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("GlyphMinAdvanceX"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float GlyphMinAdvanceX
     * }
     */
    public static final OfFloat GlyphMinAdvanceX$layout() {
        return GlyphMinAdvanceX$LAYOUT;
    }

    private static final long GlyphMinAdvanceX$OFFSET = $LAYOUT.byteOffset(groupElement("GlyphMinAdvanceX"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float GlyphMinAdvanceX
     * }
     */
    public static final long GlyphMinAdvanceX$offset() {
        return GlyphMinAdvanceX$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float GlyphMinAdvanceX
     * }
     */
    public static float GlyphMinAdvanceX(MemorySegment struct) {
        return struct.get(GlyphMinAdvanceX$LAYOUT, GlyphMinAdvanceX$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float GlyphMinAdvanceX
     * }
     */
    public static void GlyphMinAdvanceX(MemorySegment struct, float fieldValue) {
        struct.set(GlyphMinAdvanceX$LAYOUT, GlyphMinAdvanceX$OFFSET, fieldValue);
    }

    private static final OfFloat GlyphMaxAdvanceX$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("GlyphMaxAdvanceX"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float GlyphMaxAdvanceX
     * }
     */
    public static final OfFloat GlyphMaxAdvanceX$layout() {
        return GlyphMaxAdvanceX$LAYOUT;
    }

    private static final long GlyphMaxAdvanceX$OFFSET = $LAYOUT.byteOffset(groupElement("GlyphMaxAdvanceX"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float GlyphMaxAdvanceX
     * }
     */
    public static final long GlyphMaxAdvanceX$offset() {
        return GlyphMaxAdvanceX$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float GlyphMaxAdvanceX
     * }
     */
    public static float GlyphMaxAdvanceX(MemorySegment struct) {
        return struct.get(GlyphMaxAdvanceX$LAYOUT, GlyphMaxAdvanceX$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float GlyphMaxAdvanceX
     * }
     */
    public static void GlyphMaxAdvanceX(MemorySegment struct, float fieldValue) {
        struct.set(GlyphMaxAdvanceX$LAYOUT, GlyphMaxAdvanceX$OFFSET, fieldValue);
    }

    private static final OfFloat GlyphExtraAdvanceX$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("GlyphExtraAdvanceX"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float GlyphExtraAdvanceX
     * }
     */
    public static final OfFloat GlyphExtraAdvanceX$layout() {
        return GlyphExtraAdvanceX$LAYOUT;
    }

    private static final long GlyphExtraAdvanceX$OFFSET = $LAYOUT.byteOffset(groupElement("GlyphExtraAdvanceX"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float GlyphExtraAdvanceX
     * }
     */
    public static final long GlyphExtraAdvanceX$offset() {
        return GlyphExtraAdvanceX$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float GlyphExtraAdvanceX
     * }
     */
    public static float GlyphExtraAdvanceX(MemorySegment struct) {
        return struct.get(GlyphExtraAdvanceX$LAYOUT, GlyphExtraAdvanceX$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float GlyphExtraAdvanceX
     * }
     */
    public static void GlyphExtraAdvanceX(MemorySegment struct, float fieldValue) {
        struct.set(GlyphExtraAdvanceX$LAYOUT, GlyphExtraAdvanceX$OFFSET, fieldValue);
    }

    private static final OfInt FontNo$LAYOUT = (OfInt)$LAYOUT.select(groupElement("FontNo"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImU32 FontNo
     * }
     */
    public static final OfInt FontNo$layout() {
        return FontNo$LAYOUT;
    }

    private static final long FontNo$OFFSET = $LAYOUT.byteOffset(groupElement("FontNo"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImU32 FontNo
     * }
     */
    public static final long FontNo$offset() {
        return FontNo$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImU32 FontNo
     * }
     */
    public static int FontNo(MemorySegment struct) {
        return struct.get(FontNo$LAYOUT, FontNo$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImU32 FontNo
     * }
     */
    public static void FontNo(MemorySegment struct, int fieldValue) {
        struct.set(FontNo$LAYOUT, FontNo$OFFSET, fieldValue);
    }

    private static final OfInt FontLoaderFlags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("FontLoaderFlags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int FontLoaderFlags
     * }
     */
    public static final OfInt FontLoaderFlags$layout() {
        return FontLoaderFlags$LAYOUT;
    }

    private static final long FontLoaderFlags$OFFSET = $LAYOUT.byteOffset(groupElement("FontLoaderFlags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int FontLoaderFlags
     * }
     */
    public static final long FontLoaderFlags$offset() {
        return FontLoaderFlags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int FontLoaderFlags
     * }
     */
    public static int FontLoaderFlags(MemorySegment struct) {
        return struct.get(FontLoaderFlags$LAYOUT, FontLoaderFlags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int FontLoaderFlags
     * }
     */
    public static void FontLoaderFlags(MemorySegment struct, int fieldValue) {
        struct.set(FontLoaderFlags$LAYOUT, FontLoaderFlags$OFFSET, fieldValue);
    }

    private static final OfFloat RasterizerMultiply$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("RasterizerMultiply"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float RasterizerMultiply
     * }
     */
    public static final OfFloat RasterizerMultiply$layout() {
        return RasterizerMultiply$LAYOUT;
    }

    private static final long RasterizerMultiply$OFFSET = $LAYOUT.byteOffset(groupElement("RasterizerMultiply"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float RasterizerMultiply
     * }
     */
    public static final long RasterizerMultiply$offset() {
        return RasterizerMultiply$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float RasterizerMultiply
     * }
     */
    public static float RasterizerMultiply(MemorySegment struct) {
        return struct.get(RasterizerMultiply$LAYOUT, RasterizerMultiply$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float RasterizerMultiply
     * }
     */
    public static void RasterizerMultiply(MemorySegment struct, float fieldValue) {
        struct.set(RasterizerMultiply$LAYOUT, RasterizerMultiply$OFFSET, fieldValue);
    }

    private static final OfFloat RasterizerDensity$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("RasterizerDensity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float RasterizerDensity
     * }
     */
    public static final OfFloat RasterizerDensity$layout() {
        return RasterizerDensity$LAYOUT;
    }

    private static final long RasterizerDensity$OFFSET = $LAYOUT.byteOffset(groupElement("RasterizerDensity"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float RasterizerDensity
     * }
     */
    public static final long RasterizerDensity$offset() {
        return RasterizerDensity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float RasterizerDensity
     * }
     */
    public static float RasterizerDensity(MemorySegment struct) {
        return struct.get(RasterizerDensity$LAYOUT, RasterizerDensity$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float RasterizerDensity
     * }
     */
    public static void RasterizerDensity(MemorySegment struct, float fieldValue) {
        struct.set(RasterizerDensity$LAYOUT, RasterizerDensity$OFFSET, fieldValue);
    }

    private static final OfFloat ExtraSizeScale$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("ExtraSizeScale"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float ExtraSizeScale
     * }
     */
    public static final OfFloat ExtraSizeScale$layout() {
        return ExtraSizeScale$LAYOUT;
    }

    private static final long ExtraSizeScale$OFFSET = $LAYOUT.byteOffset(groupElement("ExtraSizeScale"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float ExtraSizeScale
     * }
     */
    public static final long ExtraSizeScale$offset() {
        return ExtraSizeScale$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float ExtraSizeScale
     * }
     */
    public static float ExtraSizeScale(MemorySegment struct) {
        return struct.get(ExtraSizeScale$LAYOUT, ExtraSizeScale$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float ExtraSizeScale
     * }
     */
    public static void ExtraSizeScale(MemorySegment struct, float fieldValue) {
        struct.set(ExtraSizeScale$LAYOUT, ExtraSizeScale$OFFSET, fieldValue);
    }

    private static final OfInt Flags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("Flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImFontFlags Flags
     * }
     */
    public static final OfInt Flags$layout() {
        return Flags$LAYOUT;
    }

    private static final long Flags$OFFSET = $LAYOUT.byteOffset(groupElement("Flags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImFontFlags Flags
     * }
     */
    public static final long Flags$offset() {
        return Flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImFontFlags Flags
     * }
     */
    public static int Flags(MemorySegment struct) {
        return struct.get(Flags$LAYOUT, Flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImFontFlags Flags
     * }
     */
    public static void Flags(MemorySegment struct, int fieldValue) {
        struct.set(Flags$LAYOUT, Flags$OFFSET, fieldValue);
    }

    private static final AddressLayout DstFont$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("DstFont"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImFont *DstFont
     * }
     */
    public static final AddressLayout DstFont$layout() {
        return DstFont$LAYOUT;
    }

    private static final long DstFont$OFFSET = $LAYOUT.byteOffset(groupElement("DstFont"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImFont *DstFont
     * }
     */
    public static final long DstFont$offset() {
        return DstFont$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImFont *DstFont
     * }
     */
    public static MemorySegment DstFont(MemorySegment struct) {
        return struct.get(DstFont$LAYOUT, DstFont$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImFont *DstFont
     * }
     */
    public static void DstFont(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(DstFont$LAYOUT, DstFont$OFFSET, fieldValue);
    }

    private static final AddressLayout FontLoader$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("FontLoader"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const ImFontLoader *FontLoader
     * }
     */
    public static final AddressLayout FontLoader$layout() {
        return FontLoader$LAYOUT;
    }

    private static final long FontLoader$OFFSET = $LAYOUT.byteOffset(groupElement("FontLoader"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const ImFontLoader *FontLoader
     * }
     */
    public static final long FontLoader$offset() {
        return FontLoader$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const ImFontLoader *FontLoader
     * }
     */
    public static MemorySegment FontLoader(MemorySegment struct) {
        return struct.get(FontLoader$LAYOUT, FontLoader$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const ImFontLoader *FontLoader
     * }
     */
    public static void FontLoader(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(FontLoader$LAYOUT, FontLoader$OFFSET, fieldValue);
    }

    private static final AddressLayout FontLoaderData$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("FontLoaderData"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *FontLoaderData
     * }
     */
    public static final AddressLayout FontLoaderData$layout() {
        return FontLoaderData$LAYOUT;
    }

    private static final long FontLoaderData$OFFSET = $LAYOUT.byteOffset(groupElement("FontLoaderData"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *FontLoaderData
     * }
     */
    public static final long FontLoaderData$offset() {
        return FontLoaderData$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *FontLoaderData
     * }
     */
    public static MemorySegment FontLoaderData(MemorySegment struct) {
        return struct.get(FontLoaderData$LAYOUT, FontLoaderData$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *FontLoaderData
     * }
     */
    public static void FontLoaderData(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(FontLoaderData$LAYOUT, FontLoaderData$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

