// Generated by jextract

package net.bplo.libs.jimgui.binding;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ImFontStackData {
 *     ImFont *Font;
 *     float FontSizeBeforeScaling;
 *     float FontSizeAfterScaling;
 * }
 * }
 */
public class ImFontStackData {

    ImFontStackData() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        cimgui_h.C_POINTER.withName("Font"),
        cimgui_h.C_FLOAT.withName("FontSizeBeforeScaling"),
        cimgui_h.C_FLOAT.withName("FontSizeAfterScaling")
    ).withName("ImFontStackData");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout Font$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("Font"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImFont *Font
     * }
     */
    public static final AddressLayout Font$layout() {
        return Font$LAYOUT;
    }

    private static final long Font$OFFSET = $LAYOUT.byteOffset(groupElement("Font"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImFont *Font
     * }
     */
    public static final long Font$offset() {
        return Font$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImFont *Font
     * }
     */
    public static MemorySegment Font(MemorySegment struct) {
        return struct.get(Font$LAYOUT, Font$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImFont *Font
     * }
     */
    public static void Font(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(Font$LAYOUT, Font$OFFSET, fieldValue);
    }

    private static final OfFloat FontSizeBeforeScaling$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("FontSizeBeforeScaling"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float FontSizeBeforeScaling
     * }
     */
    public static final OfFloat FontSizeBeforeScaling$layout() {
        return FontSizeBeforeScaling$LAYOUT;
    }

    private static final long FontSizeBeforeScaling$OFFSET = $LAYOUT.byteOffset(groupElement("FontSizeBeforeScaling"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float FontSizeBeforeScaling
     * }
     */
    public static final long FontSizeBeforeScaling$offset() {
        return FontSizeBeforeScaling$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float FontSizeBeforeScaling
     * }
     */
    public static float FontSizeBeforeScaling(MemorySegment struct) {
        return struct.get(FontSizeBeforeScaling$LAYOUT, FontSizeBeforeScaling$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float FontSizeBeforeScaling
     * }
     */
    public static void FontSizeBeforeScaling(MemorySegment struct, float fieldValue) {
        struct.set(FontSizeBeforeScaling$LAYOUT, FontSizeBeforeScaling$OFFSET, fieldValue);
    }

    private static final OfFloat FontSizeAfterScaling$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("FontSizeAfterScaling"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float FontSizeAfterScaling
     * }
     */
    public static final OfFloat FontSizeAfterScaling$layout() {
        return FontSizeAfterScaling$LAYOUT;
    }

    private static final long FontSizeAfterScaling$OFFSET = $LAYOUT.byteOffset(groupElement("FontSizeAfterScaling"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float FontSizeAfterScaling
     * }
     */
    public static final long FontSizeAfterScaling$offset() {
        return FontSizeAfterScaling$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float FontSizeAfterScaling
     * }
     */
    public static float FontSizeAfterScaling(MemorySegment struct) {
        return struct.get(FontSizeAfterScaling$LAYOUT, FontSizeAfterScaling$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float FontSizeAfterScaling
     * }
     */
    public static void FontSizeAfterScaling(MemorySegment struct, float fieldValue) {
        struct.set(FontSizeAfterScaling$LAYOUT, FontSizeAfterScaling$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

