// Generated by jextract

package net.bplo.libs.jimgui.binding;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ImGuiPlatformImeData {
 *     bool WantVisible;
 *     bool WantTextInput;
 *     ImVec2_c InputPos;
 *     float InputLineHeight;
 *     ImGuiID ViewportId;
 * }
 * }
 */
public class ImGuiPlatformImeData {

    ImGuiPlatformImeData() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        cimgui_h.C_BOOL.withName("WantVisible"),
        cimgui_h.C_BOOL.withName("WantTextInput"),
        MemoryLayout.paddingLayout(2),
        ImVec2_c.layout().withName("InputPos"),
        cimgui_h.C_FLOAT.withName("InputLineHeight"),
        cimgui_h.C_INT.withName("ViewportId")
    ).withName("ImGuiPlatformImeData");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfBoolean WantVisible$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("WantVisible"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool WantVisible
     * }
     */
    public static final OfBoolean WantVisible$layout() {
        return WantVisible$LAYOUT;
    }

    private static final long WantVisible$OFFSET = $LAYOUT.byteOffset(groupElement("WantVisible"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool WantVisible
     * }
     */
    public static final long WantVisible$offset() {
        return WantVisible$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool WantVisible
     * }
     */
    public static boolean WantVisible(MemorySegment struct) {
        return struct.get(WantVisible$LAYOUT, WantVisible$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool WantVisible
     * }
     */
    public static void WantVisible(MemorySegment struct, boolean fieldValue) {
        struct.set(WantVisible$LAYOUT, WantVisible$OFFSET, fieldValue);
    }

    private static final OfBoolean WantTextInput$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("WantTextInput"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool WantTextInput
     * }
     */
    public static final OfBoolean WantTextInput$layout() {
        return WantTextInput$LAYOUT;
    }

    private static final long WantTextInput$OFFSET = $LAYOUT.byteOffset(groupElement("WantTextInput"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool WantTextInput
     * }
     */
    public static final long WantTextInput$offset() {
        return WantTextInput$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool WantTextInput
     * }
     */
    public static boolean WantTextInput(MemorySegment struct) {
        return struct.get(WantTextInput$LAYOUT, WantTextInput$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool WantTextInput
     * }
     */
    public static void WantTextInput(MemorySegment struct, boolean fieldValue) {
        struct.set(WantTextInput$LAYOUT, WantTextInput$OFFSET, fieldValue);
    }

    private static final GroupLayout InputPos$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("InputPos"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec2_c InputPos
     * }
     */
    public static final GroupLayout InputPos$layout() {
        return InputPos$LAYOUT;
    }

    private static final long InputPos$OFFSET = $LAYOUT.byteOffset(groupElement("InputPos"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec2_c InputPos
     * }
     */
    public static final long InputPos$offset() {
        return InputPos$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec2_c InputPos
     * }
     */
    public static MemorySegment InputPos(MemorySegment struct) {
        return struct.asSlice(InputPos$OFFSET, InputPos$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec2_c InputPos
     * }
     */
    public static void InputPos(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, InputPos$OFFSET, InputPos$LAYOUT.byteSize());
    }

    private static final OfFloat InputLineHeight$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("InputLineHeight"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float InputLineHeight
     * }
     */
    public static final OfFloat InputLineHeight$layout() {
        return InputLineHeight$LAYOUT;
    }

    private static final long InputLineHeight$OFFSET = $LAYOUT.byteOffset(groupElement("InputLineHeight"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float InputLineHeight
     * }
     */
    public static final long InputLineHeight$offset() {
        return InputLineHeight$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float InputLineHeight
     * }
     */
    public static float InputLineHeight(MemorySegment struct) {
        return struct.get(InputLineHeight$LAYOUT, InputLineHeight$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float InputLineHeight
     * }
     */
    public static void InputLineHeight(MemorySegment struct, float fieldValue) {
        struct.set(InputLineHeight$LAYOUT, InputLineHeight$OFFSET, fieldValue);
    }

    private static final OfInt ViewportId$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ViewportId"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImGuiID ViewportId
     * }
     */
    public static final OfInt ViewportId$layout() {
        return ViewportId$LAYOUT;
    }

    private static final long ViewportId$OFFSET = $LAYOUT.byteOffset(groupElement("ViewportId"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImGuiID ViewportId
     * }
     */
    public static final long ViewportId$offset() {
        return ViewportId$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImGuiID ViewportId
     * }
     */
    public static int ViewportId(MemorySegment struct) {
        return struct.get(ViewportId$LAYOUT, ViewportId$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImGuiID ViewportId
     * }
     */
    public static void ViewportId(MemorySegment struct, int fieldValue) {
        struct.set(ViewportId$LAYOUT, ViewportId$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

