// Generated by jextract

package net.bplo.libs.jimgui.binding;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ImGuiStyle {
 *     float FontSizeBase;
 *     float FontScaleMain;
 *     float FontScaleDpi;
 *     float Alpha;
 *     float DisabledAlpha;
 *     ImVec2_c WindowPadding;
 *     float WindowRounding;
 *     float WindowBorderSize;
 *     float WindowBorderHoverPadding;
 *     ImVec2_c WindowMinSize;
 *     ImVec2_c WindowTitleAlign;
 *     ImGuiDir WindowMenuButtonPosition;
 *     float ChildRounding;
 *     float ChildBorderSize;
 *     float PopupRounding;
 *     float PopupBorderSize;
 *     ImVec2_c FramePadding;
 *     float FrameRounding;
 *     float FrameBorderSize;
 *     ImVec2_c ItemSpacing;
 *     ImVec2_c ItemInnerSpacing;
 *     ImVec2_c CellPadding;
 *     ImVec2_c TouchExtraPadding;
 *     float IndentSpacing;
 *     float ColumnsMinSpacing;
 *     float ScrollbarSize;
 *     float ScrollbarRounding;
 *     float ScrollbarPadding;
 *     float GrabMinSize;
 *     float GrabRounding;
 *     float LogSliderDeadzone;
 *     float ImageRounding;
 *     float ImageBorderSize;
 *     float TabRounding;
 *     float TabBorderSize;
 *     float TabMinWidthBase;
 *     float TabMinWidthShrink;
 *     float TabCloseButtonMinWidthSelected;
 *     float TabCloseButtonMinWidthUnselected;
 *     float TabBarBorderSize;
 *     float TabBarOverlineSize;
 *     float TableAngledHeadersAngle;
 *     ImVec2_c TableAngledHeadersTextAlign;
 *     ImGuiTreeNodeFlags TreeLinesFlags;
 *     float TreeLinesSize;
 *     float TreeLinesRounding;
 *     float DragDropTargetRounding;
 *     float DragDropTargetBorderSize;
 *     float DragDropTargetPadding;
 *     float ColorMarkerSize;
 *     ImGuiDir ColorButtonPosition;
 *     ImVec2_c ButtonTextAlign;
 *     ImVec2_c SelectableTextAlign;
 *     float SeparatorTextBorderSize;
 *     ImVec2_c SeparatorTextAlign;
 *     ImVec2_c SeparatorTextPadding;
 *     ImVec2_c DisplayWindowPadding;
 *     ImVec2_c DisplaySafeAreaPadding;
 *     float MouseCursorScale;
 *     bool AntiAliasedLines;
 *     bool AntiAliasedLinesUseTex;
 *     bool AntiAliasedFill;
 *     float CurveTessellationTol;
 *     float CircleTessellationMaxError;
 *     ImVec4_c Colors[60];
 *     float HoverStationaryDelay;
 *     float HoverDelayShort;
 *     float HoverDelayNormal;
 *     ImGuiHoveredFlags HoverFlagsForTooltipMouse;
 *     ImGuiHoveredFlags HoverFlagsForTooltipNav;
 *     float _MainScale;
 *     float _NextFrameFontSizeBase;
 * }
 * }
 */
public class ImGuiStyle {

    ImGuiStyle() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        cimgui_h.C_FLOAT.withName("FontSizeBase"),
        cimgui_h.C_FLOAT.withName("FontScaleMain"),
        cimgui_h.C_FLOAT.withName("FontScaleDpi"),
        cimgui_h.C_FLOAT.withName("Alpha"),
        cimgui_h.C_FLOAT.withName("DisabledAlpha"),
        ImVec2_c.layout().withName("WindowPadding"),
        cimgui_h.C_FLOAT.withName("WindowRounding"),
        cimgui_h.C_FLOAT.withName("WindowBorderSize"),
        cimgui_h.C_FLOAT.withName("WindowBorderHoverPadding"),
        ImVec2_c.layout().withName("WindowMinSize"),
        ImVec2_c.layout().withName("WindowTitleAlign"),
        cimgui_h.C_INT.withName("WindowMenuButtonPosition"),
        cimgui_h.C_FLOAT.withName("ChildRounding"),
        cimgui_h.C_FLOAT.withName("ChildBorderSize"),
        cimgui_h.C_FLOAT.withName("PopupRounding"),
        cimgui_h.C_FLOAT.withName("PopupBorderSize"),
        ImVec2_c.layout().withName("FramePadding"),
        cimgui_h.C_FLOAT.withName("FrameRounding"),
        cimgui_h.C_FLOAT.withName("FrameBorderSize"),
        ImVec2_c.layout().withName("ItemSpacing"),
        ImVec2_c.layout().withName("ItemInnerSpacing"),
        ImVec2_c.layout().withName("CellPadding"),
        ImVec2_c.layout().withName("TouchExtraPadding"),
        cimgui_h.C_FLOAT.withName("IndentSpacing"),
        cimgui_h.C_FLOAT.withName("ColumnsMinSpacing"),
        cimgui_h.C_FLOAT.withName("ScrollbarSize"),
        cimgui_h.C_FLOAT.withName("ScrollbarRounding"),
        cimgui_h.C_FLOAT.withName("ScrollbarPadding"),
        cimgui_h.C_FLOAT.withName("GrabMinSize"),
        cimgui_h.C_FLOAT.withName("GrabRounding"),
        cimgui_h.C_FLOAT.withName("LogSliderDeadzone"),
        cimgui_h.C_FLOAT.withName("ImageRounding"),
        cimgui_h.C_FLOAT.withName("ImageBorderSize"),
        cimgui_h.C_FLOAT.withName("TabRounding"),
        cimgui_h.C_FLOAT.withName("TabBorderSize"),
        cimgui_h.C_FLOAT.withName("TabMinWidthBase"),
        cimgui_h.C_FLOAT.withName("TabMinWidthShrink"),
        cimgui_h.C_FLOAT.withName("TabCloseButtonMinWidthSelected"),
        cimgui_h.C_FLOAT.withName("TabCloseButtonMinWidthUnselected"),
        cimgui_h.C_FLOAT.withName("TabBarBorderSize"),
        cimgui_h.C_FLOAT.withName("TabBarOverlineSize"),
        cimgui_h.C_FLOAT.withName("TableAngledHeadersAngle"),
        ImVec2_c.layout().withName("TableAngledHeadersTextAlign"),
        cimgui_h.C_INT.withName("TreeLinesFlags"),
        cimgui_h.C_FLOAT.withName("TreeLinesSize"),
        cimgui_h.C_FLOAT.withName("TreeLinesRounding"),
        cimgui_h.C_FLOAT.withName("DragDropTargetRounding"),
        cimgui_h.C_FLOAT.withName("DragDropTargetBorderSize"),
        cimgui_h.C_FLOAT.withName("DragDropTargetPadding"),
        cimgui_h.C_FLOAT.withName("ColorMarkerSize"),
        cimgui_h.C_INT.withName("ColorButtonPosition"),
        ImVec2_c.layout().withName("ButtonTextAlign"),
        ImVec2_c.layout().withName("SelectableTextAlign"),
        cimgui_h.C_FLOAT.withName("SeparatorTextBorderSize"),
        ImVec2_c.layout().withName("SeparatorTextAlign"),
        ImVec2_c.layout().withName("SeparatorTextPadding"),
        ImVec2_c.layout().withName("DisplayWindowPadding"),
        ImVec2_c.layout().withName("DisplaySafeAreaPadding"),
        cimgui_h.C_FLOAT.withName("MouseCursorScale"),
        cimgui_h.C_BOOL.withName("AntiAliasedLines"),
        cimgui_h.C_BOOL.withName("AntiAliasedLinesUseTex"),
        cimgui_h.C_BOOL.withName("AntiAliasedFill"),
        MemoryLayout.paddingLayout(1),
        cimgui_h.C_FLOAT.withName("CurveTessellationTol"),
        cimgui_h.C_FLOAT.withName("CircleTessellationMaxError"),
        MemoryLayout.sequenceLayout(60, ImVec4_c.layout()).withName("Colors"),
        cimgui_h.C_FLOAT.withName("HoverStationaryDelay"),
        cimgui_h.C_FLOAT.withName("HoverDelayShort"),
        cimgui_h.C_FLOAT.withName("HoverDelayNormal"),
        cimgui_h.C_INT.withName("HoverFlagsForTooltipMouse"),
        cimgui_h.C_INT.withName("HoverFlagsForTooltipNav"),
        cimgui_h.C_FLOAT.withName("_MainScale"),
        cimgui_h.C_FLOAT.withName("_NextFrameFontSizeBase")
    ).withName("ImGuiStyle");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfFloat FontSizeBase$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("FontSizeBase"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float FontSizeBase
     * }
     */
    public static final OfFloat FontSizeBase$layout() {
        return FontSizeBase$LAYOUT;
    }

    private static final long FontSizeBase$OFFSET = $LAYOUT.byteOffset(groupElement("FontSizeBase"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float FontSizeBase
     * }
     */
    public static final long FontSizeBase$offset() {
        return FontSizeBase$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float FontSizeBase
     * }
     */
    public static float FontSizeBase(MemorySegment struct) {
        return struct.get(FontSizeBase$LAYOUT, FontSizeBase$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float FontSizeBase
     * }
     */
    public static void FontSizeBase(MemorySegment struct, float fieldValue) {
        struct.set(FontSizeBase$LAYOUT, FontSizeBase$OFFSET, fieldValue);
    }

    private static final OfFloat FontScaleMain$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("FontScaleMain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float FontScaleMain
     * }
     */
    public static final OfFloat FontScaleMain$layout() {
        return FontScaleMain$LAYOUT;
    }

    private static final long FontScaleMain$OFFSET = $LAYOUT.byteOffset(groupElement("FontScaleMain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float FontScaleMain
     * }
     */
    public static final long FontScaleMain$offset() {
        return FontScaleMain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float FontScaleMain
     * }
     */
    public static float FontScaleMain(MemorySegment struct) {
        return struct.get(FontScaleMain$LAYOUT, FontScaleMain$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float FontScaleMain
     * }
     */
    public static void FontScaleMain(MemorySegment struct, float fieldValue) {
        struct.set(FontScaleMain$LAYOUT, FontScaleMain$OFFSET, fieldValue);
    }

    private static final OfFloat FontScaleDpi$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("FontScaleDpi"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float FontScaleDpi
     * }
     */
    public static final OfFloat FontScaleDpi$layout() {
        return FontScaleDpi$LAYOUT;
    }

    private static final long FontScaleDpi$OFFSET = $LAYOUT.byteOffset(groupElement("FontScaleDpi"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float FontScaleDpi
     * }
     */
    public static final long FontScaleDpi$offset() {
        return FontScaleDpi$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float FontScaleDpi
     * }
     */
    public static float FontScaleDpi(MemorySegment struct) {
        return struct.get(FontScaleDpi$LAYOUT, FontScaleDpi$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float FontScaleDpi
     * }
     */
    public static void FontScaleDpi(MemorySegment struct, float fieldValue) {
        struct.set(FontScaleDpi$LAYOUT, FontScaleDpi$OFFSET, fieldValue);
    }

    private static final OfFloat Alpha$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("Alpha"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float Alpha
     * }
     */
    public static final OfFloat Alpha$layout() {
        return Alpha$LAYOUT;
    }

    private static final long Alpha$OFFSET = $LAYOUT.byteOffset(groupElement("Alpha"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float Alpha
     * }
     */
    public static final long Alpha$offset() {
        return Alpha$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float Alpha
     * }
     */
    public static float Alpha(MemorySegment struct) {
        return struct.get(Alpha$LAYOUT, Alpha$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float Alpha
     * }
     */
    public static void Alpha(MemorySegment struct, float fieldValue) {
        struct.set(Alpha$LAYOUT, Alpha$OFFSET, fieldValue);
    }

    private static final OfFloat DisabledAlpha$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("DisabledAlpha"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float DisabledAlpha
     * }
     */
    public static final OfFloat DisabledAlpha$layout() {
        return DisabledAlpha$LAYOUT;
    }

    private static final long DisabledAlpha$OFFSET = $LAYOUT.byteOffset(groupElement("DisabledAlpha"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float DisabledAlpha
     * }
     */
    public static final long DisabledAlpha$offset() {
        return DisabledAlpha$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float DisabledAlpha
     * }
     */
    public static float DisabledAlpha(MemorySegment struct) {
        return struct.get(DisabledAlpha$LAYOUT, DisabledAlpha$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float DisabledAlpha
     * }
     */
    public static void DisabledAlpha(MemorySegment struct, float fieldValue) {
        struct.set(DisabledAlpha$LAYOUT, DisabledAlpha$OFFSET, fieldValue);
    }

    private static final GroupLayout WindowPadding$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("WindowPadding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec2_c WindowPadding
     * }
     */
    public static final GroupLayout WindowPadding$layout() {
        return WindowPadding$LAYOUT;
    }

    private static final long WindowPadding$OFFSET = $LAYOUT.byteOffset(groupElement("WindowPadding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec2_c WindowPadding
     * }
     */
    public static final long WindowPadding$offset() {
        return WindowPadding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec2_c WindowPadding
     * }
     */
    public static MemorySegment WindowPadding(MemorySegment struct) {
        return struct.asSlice(WindowPadding$OFFSET, WindowPadding$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec2_c WindowPadding
     * }
     */
    public static void WindowPadding(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, WindowPadding$OFFSET, WindowPadding$LAYOUT.byteSize());
    }

    private static final OfFloat WindowRounding$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("WindowRounding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float WindowRounding
     * }
     */
    public static final OfFloat WindowRounding$layout() {
        return WindowRounding$LAYOUT;
    }

    private static final long WindowRounding$OFFSET = $LAYOUT.byteOffset(groupElement("WindowRounding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float WindowRounding
     * }
     */
    public static final long WindowRounding$offset() {
        return WindowRounding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float WindowRounding
     * }
     */
    public static float WindowRounding(MemorySegment struct) {
        return struct.get(WindowRounding$LAYOUT, WindowRounding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float WindowRounding
     * }
     */
    public static void WindowRounding(MemorySegment struct, float fieldValue) {
        struct.set(WindowRounding$LAYOUT, WindowRounding$OFFSET, fieldValue);
    }

    private static final OfFloat WindowBorderSize$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("WindowBorderSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float WindowBorderSize
     * }
     */
    public static final OfFloat WindowBorderSize$layout() {
        return WindowBorderSize$LAYOUT;
    }

    private static final long WindowBorderSize$OFFSET = $LAYOUT.byteOffset(groupElement("WindowBorderSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float WindowBorderSize
     * }
     */
    public static final long WindowBorderSize$offset() {
        return WindowBorderSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float WindowBorderSize
     * }
     */
    public static float WindowBorderSize(MemorySegment struct) {
        return struct.get(WindowBorderSize$LAYOUT, WindowBorderSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float WindowBorderSize
     * }
     */
    public static void WindowBorderSize(MemorySegment struct, float fieldValue) {
        struct.set(WindowBorderSize$LAYOUT, WindowBorderSize$OFFSET, fieldValue);
    }

    private static final OfFloat WindowBorderHoverPadding$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("WindowBorderHoverPadding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float WindowBorderHoverPadding
     * }
     */
    public static final OfFloat WindowBorderHoverPadding$layout() {
        return WindowBorderHoverPadding$LAYOUT;
    }

    private static final long WindowBorderHoverPadding$OFFSET = $LAYOUT.byteOffset(groupElement("WindowBorderHoverPadding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float WindowBorderHoverPadding
     * }
     */
    public static final long WindowBorderHoverPadding$offset() {
        return WindowBorderHoverPadding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float WindowBorderHoverPadding
     * }
     */
    public static float WindowBorderHoverPadding(MemorySegment struct) {
        return struct.get(WindowBorderHoverPadding$LAYOUT, WindowBorderHoverPadding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float WindowBorderHoverPadding
     * }
     */
    public static void WindowBorderHoverPadding(MemorySegment struct, float fieldValue) {
        struct.set(WindowBorderHoverPadding$LAYOUT, WindowBorderHoverPadding$OFFSET, fieldValue);
    }

    private static final GroupLayout WindowMinSize$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("WindowMinSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec2_c WindowMinSize
     * }
     */
    public static final GroupLayout WindowMinSize$layout() {
        return WindowMinSize$LAYOUT;
    }

    private static final long WindowMinSize$OFFSET = $LAYOUT.byteOffset(groupElement("WindowMinSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec2_c WindowMinSize
     * }
     */
    public static final long WindowMinSize$offset() {
        return WindowMinSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec2_c WindowMinSize
     * }
     */
    public static MemorySegment WindowMinSize(MemorySegment struct) {
        return struct.asSlice(WindowMinSize$OFFSET, WindowMinSize$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec2_c WindowMinSize
     * }
     */
    public static void WindowMinSize(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, WindowMinSize$OFFSET, WindowMinSize$LAYOUT.byteSize());
    }

    private static final GroupLayout WindowTitleAlign$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("WindowTitleAlign"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec2_c WindowTitleAlign
     * }
     */
    public static final GroupLayout WindowTitleAlign$layout() {
        return WindowTitleAlign$LAYOUT;
    }

    private static final long WindowTitleAlign$OFFSET = $LAYOUT.byteOffset(groupElement("WindowTitleAlign"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec2_c WindowTitleAlign
     * }
     */
    public static final long WindowTitleAlign$offset() {
        return WindowTitleAlign$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec2_c WindowTitleAlign
     * }
     */
    public static MemorySegment WindowTitleAlign(MemorySegment struct) {
        return struct.asSlice(WindowTitleAlign$OFFSET, WindowTitleAlign$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec2_c WindowTitleAlign
     * }
     */
    public static void WindowTitleAlign(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, WindowTitleAlign$OFFSET, WindowTitleAlign$LAYOUT.byteSize());
    }

    private static final OfInt WindowMenuButtonPosition$LAYOUT = (OfInt)$LAYOUT.select(groupElement("WindowMenuButtonPosition"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImGuiDir WindowMenuButtonPosition
     * }
     */
    public static final OfInt WindowMenuButtonPosition$layout() {
        return WindowMenuButtonPosition$LAYOUT;
    }

    private static final long WindowMenuButtonPosition$OFFSET = $LAYOUT.byteOffset(groupElement("WindowMenuButtonPosition"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImGuiDir WindowMenuButtonPosition
     * }
     */
    public static final long WindowMenuButtonPosition$offset() {
        return WindowMenuButtonPosition$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImGuiDir WindowMenuButtonPosition
     * }
     */
    public static int WindowMenuButtonPosition(MemorySegment struct) {
        return struct.get(WindowMenuButtonPosition$LAYOUT, WindowMenuButtonPosition$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImGuiDir WindowMenuButtonPosition
     * }
     */
    public static void WindowMenuButtonPosition(MemorySegment struct, int fieldValue) {
        struct.set(WindowMenuButtonPosition$LAYOUT, WindowMenuButtonPosition$OFFSET, fieldValue);
    }

    private static final OfFloat ChildRounding$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("ChildRounding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float ChildRounding
     * }
     */
    public static final OfFloat ChildRounding$layout() {
        return ChildRounding$LAYOUT;
    }

    private static final long ChildRounding$OFFSET = $LAYOUT.byteOffset(groupElement("ChildRounding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float ChildRounding
     * }
     */
    public static final long ChildRounding$offset() {
        return ChildRounding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float ChildRounding
     * }
     */
    public static float ChildRounding(MemorySegment struct) {
        return struct.get(ChildRounding$LAYOUT, ChildRounding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float ChildRounding
     * }
     */
    public static void ChildRounding(MemorySegment struct, float fieldValue) {
        struct.set(ChildRounding$LAYOUT, ChildRounding$OFFSET, fieldValue);
    }

    private static final OfFloat ChildBorderSize$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("ChildBorderSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float ChildBorderSize
     * }
     */
    public static final OfFloat ChildBorderSize$layout() {
        return ChildBorderSize$LAYOUT;
    }

    private static final long ChildBorderSize$OFFSET = $LAYOUT.byteOffset(groupElement("ChildBorderSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float ChildBorderSize
     * }
     */
    public static final long ChildBorderSize$offset() {
        return ChildBorderSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float ChildBorderSize
     * }
     */
    public static float ChildBorderSize(MemorySegment struct) {
        return struct.get(ChildBorderSize$LAYOUT, ChildBorderSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float ChildBorderSize
     * }
     */
    public static void ChildBorderSize(MemorySegment struct, float fieldValue) {
        struct.set(ChildBorderSize$LAYOUT, ChildBorderSize$OFFSET, fieldValue);
    }

    private static final OfFloat PopupRounding$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("PopupRounding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float PopupRounding
     * }
     */
    public static final OfFloat PopupRounding$layout() {
        return PopupRounding$LAYOUT;
    }

    private static final long PopupRounding$OFFSET = $LAYOUT.byteOffset(groupElement("PopupRounding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float PopupRounding
     * }
     */
    public static final long PopupRounding$offset() {
        return PopupRounding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float PopupRounding
     * }
     */
    public static float PopupRounding(MemorySegment struct) {
        return struct.get(PopupRounding$LAYOUT, PopupRounding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float PopupRounding
     * }
     */
    public static void PopupRounding(MemorySegment struct, float fieldValue) {
        struct.set(PopupRounding$LAYOUT, PopupRounding$OFFSET, fieldValue);
    }

    private static final OfFloat PopupBorderSize$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("PopupBorderSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float PopupBorderSize
     * }
     */
    public static final OfFloat PopupBorderSize$layout() {
        return PopupBorderSize$LAYOUT;
    }

    private static final long PopupBorderSize$OFFSET = $LAYOUT.byteOffset(groupElement("PopupBorderSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float PopupBorderSize
     * }
     */
    public static final long PopupBorderSize$offset() {
        return PopupBorderSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float PopupBorderSize
     * }
     */
    public static float PopupBorderSize(MemorySegment struct) {
        return struct.get(PopupBorderSize$LAYOUT, PopupBorderSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float PopupBorderSize
     * }
     */
    public static void PopupBorderSize(MemorySegment struct, float fieldValue) {
        struct.set(PopupBorderSize$LAYOUT, PopupBorderSize$OFFSET, fieldValue);
    }

    private static final GroupLayout FramePadding$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("FramePadding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec2_c FramePadding
     * }
     */
    public static final GroupLayout FramePadding$layout() {
        return FramePadding$LAYOUT;
    }

    private static final long FramePadding$OFFSET = $LAYOUT.byteOffset(groupElement("FramePadding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec2_c FramePadding
     * }
     */
    public static final long FramePadding$offset() {
        return FramePadding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec2_c FramePadding
     * }
     */
    public static MemorySegment FramePadding(MemorySegment struct) {
        return struct.asSlice(FramePadding$OFFSET, FramePadding$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec2_c FramePadding
     * }
     */
    public static void FramePadding(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, FramePadding$OFFSET, FramePadding$LAYOUT.byteSize());
    }

    private static final OfFloat FrameRounding$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("FrameRounding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float FrameRounding
     * }
     */
    public static final OfFloat FrameRounding$layout() {
        return FrameRounding$LAYOUT;
    }

    private static final long FrameRounding$OFFSET = $LAYOUT.byteOffset(groupElement("FrameRounding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float FrameRounding
     * }
     */
    public static final long FrameRounding$offset() {
        return FrameRounding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float FrameRounding
     * }
     */
    public static float FrameRounding(MemorySegment struct) {
        return struct.get(FrameRounding$LAYOUT, FrameRounding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float FrameRounding
     * }
     */
    public static void FrameRounding(MemorySegment struct, float fieldValue) {
        struct.set(FrameRounding$LAYOUT, FrameRounding$OFFSET, fieldValue);
    }

    private static final OfFloat FrameBorderSize$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("FrameBorderSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float FrameBorderSize
     * }
     */
    public static final OfFloat FrameBorderSize$layout() {
        return FrameBorderSize$LAYOUT;
    }

    private static final long FrameBorderSize$OFFSET = $LAYOUT.byteOffset(groupElement("FrameBorderSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float FrameBorderSize
     * }
     */
    public static final long FrameBorderSize$offset() {
        return FrameBorderSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float FrameBorderSize
     * }
     */
    public static float FrameBorderSize(MemorySegment struct) {
        return struct.get(FrameBorderSize$LAYOUT, FrameBorderSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float FrameBorderSize
     * }
     */
    public static void FrameBorderSize(MemorySegment struct, float fieldValue) {
        struct.set(FrameBorderSize$LAYOUT, FrameBorderSize$OFFSET, fieldValue);
    }

    private static final GroupLayout ItemSpacing$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("ItemSpacing"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec2_c ItemSpacing
     * }
     */
    public static final GroupLayout ItemSpacing$layout() {
        return ItemSpacing$LAYOUT;
    }

    private static final long ItemSpacing$OFFSET = $LAYOUT.byteOffset(groupElement("ItemSpacing"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec2_c ItemSpacing
     * }
     */
    public static final long ItemSpacing$offset() {
        return ItemSpacing$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec2_c ItemSpacing
     * }
     */
    public static MemorySegment ItemSpacing(MemorySegment struct) {
        return struct.asSlice(ItemSpacing$OFFSET, ItemSpacing$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec2_c ItemSpacing
     * }
     */
    public static void ItemSpacing(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ItemSpacing$OFFSET, ItemSpacing$LAYOUT.byteSize());
    }

    private static final GroupLayout ItemInnerSpacing$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("ItemInnerSpacing"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec2_c ItemInnerSpacing
     * }
     */
    public static final GroupLayout ItemInnerSpacing$layout() {
        return ItemInnerSpacing$LAYOUT;
    }

    private static final long ItemInnerSpacing$OFFSET = $LAYOUT.byteOffset(groupElement("ItemInnerSpacing"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec2_c ItemInnerSpacing
     * }
     */
    public static final long ItemInnerSpacing$offset() {
        return ItemInnerSpacing$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec2_c ItemInnerSpacing
     * }
     */
    public static MemorySegment ItemInnerSpacing(MemorySegment struct) {
        return struct.asSlice(ItemInnerSpacing$OFFSET, ItemInnerSpacing$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec2_c ItemInnerSpacing
     * }
     */
    public static void ItemInnerSpacing(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ItemInnerSpacing$OFFSET, ItemInnerSpacing$LAYOUT.byteSize());
    }

    private static final GroupLayout CellPadding$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("CellPadding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec2_c CellPadding
     * }
     */
    public static final GroupLayout CellPadding$layout() {
        return CellPadding$LAYOUT;
    }

    private static final long CellPadding$OFFSET = $LAYOUT.byteOffset(groupElement("CellPadding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec2_c CellPadding
     * }
     */
    public static final long CellPadding$offset() {
        return CellPadding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec2_c CellPadding
     * }
     */
    public static MemorySegment CellPadding(MemorySegment struct) {
        return struct.asSlice(CellPadding$OFFSET, CellPadding$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec2_c CellPadding
     * }
     */
    public static void CellPadding(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, CellPadding$OFFSET, CellPadding$LAYOUT.byteSize());
    }

    private static final GroupLayout TouchExtraPadding$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("TouchExtraPadding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec2_c TouchExtraPadding
     * }
     */
    public static final GroupLayout TouchExtraPadding$layout() {
        return TouchExtraPadding$LAYOUT;
    }

    private static final long TouchExtraPadding$OFFSET = $LAYOUT.byteOffset(groupElement("TouchExtraPadding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec2_c TouchExtraPadding
     * }
     */
    public static final long TouchExtraPadding$offset() {
        return TouchExtraPadding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec2_c TouchExtraPadding
     * }
     */
    public static MemorySegment TouchExtraPadding(MemorySegment struct) {
        return struct.asSlice(TouchExtraPadding$OFFSET, TouchExtraPadding$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec2_c TouchExtraPadding
     * }
     */
    public static void TouchExtraPadding(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, TouchExtraPadding$OFFSET, TouchExtraPadding$LAYOUT.byteSize());
    }

    private static final OfFloat IndentSpacing$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("IndentSpacing"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float IndentSpacing
     * }
     */
    public static final OfFloat IndentSpacing$layout() {
        return IndentSpacing$LAYOUT;
    }

    private static final long IndentSpacing$OFFSET = $LAYOUT.byteOffset(groupElement("IndentSpacing"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float IndentSpacing
     * }
     */
    public static final long IndentSpacing$offset() {
        return IndentSpacing$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float IndentSpacing
     * }
     */
    public static float IndentSpacing(MemorySegment struct) {
        return struct.get(IndentSpacing$LAYOUT, IndentSpacing$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float IndentSpacing
     * }
     */
    public static void IndentSpacing(MemorySegment struct, float fieldValue) {
        struct.set(IndentSpacing$LAYOUT, IndentSpacing$OFFSET, fieldValue);
    }

    private static final OfFloat ColumnsMinSpacing$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("ColumnsMinSpacing"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float ColumnsMinSpacing
     * }
     */
    public static final OfFloat ColumnsMinSpacing$layout() {
        return ColumnsMinSpacing$LAYOUT;
    }

    private static final long ColumnsMinSpacing$OFFSET = $LAYOUT.byteOffset(groupElement("ColumnsMinSpacing"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float ColumnsMinSpacing
     * }
     */
    public static final long ColumnsMinSpacing$offset() {
        return ColumnsMinSpacing$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float ColumnsMinSpacing
     * }
     */
    public static float ColumnsMinSpacing(MemorySegment struct) {
        return struct.get(ColumnsMinSpacing$LAYOUT, ColumnsMinSpacing$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float ColumnsMinSpacing
     * }
     */
    public static void ColumnsMinSpacing(MemorySegment struct, float fieldValue) {
        struct.set(ColumnsMinSpacing$LAYOUT, ColumnsMinSpacing$OFFSET, fieldValue);
    }

    private static final OfFloat ScrollbarSize$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("ScrollbarSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float ScrollbarSize
     * }
     */
    public static final OfFloat ScrollbarSize$layout() {
        return ScrollbarSize$LAYOUT;
    }

    private static final long ScrollbarSize$OFFSET = $LAYOUT.byteOffset(groupElement("ScrollbarSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float ScrollbarSize
     * }
     */
    public static final long ScrollbarSize$offset() {
        return ScrollbarSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float ScrollbarSize
     * }
     */
    public static float ScrollbarSize(MemorySegment struct) {
        return struct.get(ScrollbarSize$LAYOUT, ScrollbarSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float ScrollbarSize
     * }
     */
    public static void ScrollbarSize(MemorySegment struct, float fieldValue) {
        struct.set(ScrollbarSize$LAYOUT, ScrollbarSize$OFFSET, fieldValue);
    }

    private static final OfFloat ScrollbarRounding$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("ScrollbarRounding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float ScrollbarRounding
     * }
     */
    public static final OfFloat ScrollbarRounding$layout() {
        return ScrollbarRounding$LAYOUT;
    }

    private static final long ScrollbarRounding$OFFSET = $LAYOUT.byteOffset(groupElement("ScrollbarRounding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float ScrollbarRounding
     * }
     */
    public static final long ScrollbarRounding$offset() {
        return ScrollbarRounding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float ScrollbarRounding
     * }
     */
    public static float ScrollbarRounding(MemorySegment struct) {
        return struct.get(ScrollbarRounding$LAYOUT, ScrollbarRounding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float ScrollbarRounding
     * }
     */
    public static void ScrollbarRounding(MemorySegment struct, float fieldValue) {
        struct.set(ScrollbarRounding$LAYOUT, ScrollbarRounding$OFFSET, fieldValue);
    }

    private static final OfFloat ScrollbarPadding$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("ScrollbarPadding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float ScrollbarPadding
     * }
     */
    public static final OfFloat ScrollbarPadding$layout() {
        return ScrollbarPadding$LAYOUT;
    }

    private static final long ScrollbarPadding$OFFSET = $LAYOUT.byteOffset(groupElement("ScrollbarPadding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float ScrollbarPadding
     * }
     */
    public static final long ScrollbarPadding$offset() {
        return ScrollbarPadding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float ScrollbarPadding
     * }
     */
    public static float ScrollbarPadding(MemorySegment struct) {
        return struct.get(ScrollbarPadding$LAYOUT, ScrollbarPadding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float ScrollbarPadding
     * }
     */
    public static void ScrollbarPadding(MemorySegment struct, float fieldValue) {
        struct.set(ScrollbarPadding$LAYOUT, ScrollbarPadding$OFFSET, fieldValue);
    }

    private static final OfFloat GrabMinSize$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("GrabMinSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float GrabMinSize
     * }
     */
    public static final OfFloat GrabMinSize$layout() {
        return GrabMinSize$LAYOUT;
    }

    private static final long GrabMinSize$OFFSET = $LAYOUT.byteOffset(groupElement("GrabMinSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float GrabMinSize
     * }
     */
    public static final long GrabMinSize$offset() {
        return GrabMinSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float GrabMinSize
     * }
     */
    public static float GrabMinSize(MemorySegment struct) {
        return struct.get(GrabMinSize$LAYOUT, GrabMinSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float GrabMinSize
     * }
     */
    public static void GrabMinSize(MemorySegment struct, float fieldValue) {
        struct.set(GrabMinSize$LAYOUT, GrabMinSize$OFFSET, fieldValue);
    }

    private static final OfFloat GrabRounding$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("GrabRounding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float GrabRounding
     * }
     */
    public static final OfFloat GrabRounding$layout() {
        return GrabRounding$LAYOUT;
    }

    private static final long GrabRounding$OFFSET = $LAYOUT.byteOffset(groupElement("GrabRounding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float GrabRounding
     * }
     */
    public static final long GrabRounding$offset() {
        return GrabRounding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float GrabRounding
     * }
     */
    public static float GrabRounding(MemorySegment struct) {
        return struct.get(GrabRounding$LAYOUT, GrabRounding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float GrabRounding
     * }
     */
    public static void GrabRounding(MemorySegment struct, float fieldValue) {
        struct.set(GrabRounding$LAYOUT, GrabRounding$OFFSET, fieldValue);
    }

    private static final OfFloat LogSliderDeadzone$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("LogSliderDeadzone"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float LogSliderDeadzone
     * }
     */
    public static final OfFloat LogSliderDeadzone$layout() {
        return LogSliderDeadzone$LAYOUT;
    }

    private static final long LogSliderDeadzone$OFFSET = $LAYOUT.byteOffset(groupElement("LogSliderDeadzone"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float LogSliderDeadzone
     * }
     */
    public static final long LogSliderDeadzone$offset() {
        return LogSliderDeadzone$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float LogSliderDeadzone
     * }
     */
    public static float LogSliderDeadzone(MemorySegment struct) {
        return struct.get(LogSliderDeadzone$LAYOUT, LogSliderDeadzone$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float LogSliderDeadzone
     * }
     */
    public static void LogSliderDeadzone(MemorySegment struct, float fieldValue) {
        struct.set(LogSliderDeadzone$LAYOUT, LogSliderDeadzone$OFFSET, fieldValue);
    }

    private static final OfFloat ImageRounding$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("ImageRounding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float ImageRounding
     * }
     */
    public static final OfFloat ImageRounding$layout() {
        return ImageRounding$LAYOUT;
    }

    private static final long ImageRounding$OFFSET = $LAYOUT.byteOffset(groupElement("ImageRounding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float ImageRounding
     * }
     */
    public static final long ImageRounding$offset() {
        return ImageRounding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float ImageRounding
     * }
     */
    public static float ImageRounding(MemorySegment struct) {
        return struct.get(ImageRounding$LAYOUT, ImageRounding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float ImageRounding
     * }
     */
    public static void ImageRounding(MemorySegment struct, float fieldValue) {
        struct.set(ImageRounding$LAYOUT, ImageRounding$OFFSET, fieldValue);
    }

    private static final OfFloat ImageBorderSize$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("ImageBorderSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float ImageBorderSize
     * }
     */
    public static final OfFloat ImageBorderSize$layout() {
        return ImageBorderSize$LAYOUT;
    }

    private static final long ImageBorderSize$OFFSET = $LAYOUT.byteOffset(groupElement("ImageBorderSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float ImageBorderSize
     * }
     */
    public static final long ImageBorderSize$offset() {
        return ImageBorderSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float ImageBorderSize
     * }
     */
    public static float ImageBorderSize(MemorySegment struct) {
        return struct.get(ImageBorderSize$LAYOUT, ImageBorderSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float ImageBorderSize
     * }
     */
    public static void ImageBorderSize(MemorySegment struct, float fieldValue) {
        struct.set(ImageBorderSize$LAYOUT, ImageBorderSize$OFFSET, fieldValue);
    }

    private static final OfFloat TabRounding$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("TabRounding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float TabRounding
     * }
     */
    public static final OfFloat TabRounding$layout() {
        return TabRounding$LAYOUT;
    }

    private static final long TabRounding$OFFSET = $LAYOUT.byteOffset(groupElement("TabRounding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float TabRounding
     * }
     */
    public static final long TabRounding$offset() {
        return TabRounding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float TabRounding
     * }
     */
    public static float TabRounding(MemorySegment struct) {
        return struct.get(TabRounding$LAYOUT, TabRounding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float TabRounding
     * }
     */
    public static void TabRounding(MemorySegment struct, float fieldValue) {
        struct.set(TabRounding$LAYOUT, TabRounding$OFFSET, fieldValue);
    }

    private static final OfFloat TabBorderSize$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("TabBorderSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float TabBorderSize
     * }
     */
    public static final OfFloat TabBorderSize$layout() {
        return TabBorderSize$LAYOUT;
    }

    private static final long TabBorderSize$OFFSET = $LAYOUT.byteOffset(groupElement("TabBorderSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float TabBorderSize
     * }
     */
    public static final long TabBorderSize$offset() {
        return TabBorderSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float TabBorderSize
     * }
     */
    public static float TabBorderSize(MemorySegment struct) {
        return struct.get(TabBorderSize$LAYOUT, TabBorderSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float TabBorderSize
     * }
     */
    public static void TabBorderSize(MemorySegment struct, float fieldValue) {
        struct.set(TabBorderSize$LAYOUT, TabBorderSize$OFFSET, fieldValue);
    }

    private static final OfFloat TabMinWidthBase$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("TabMinWidthBase"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float TabMinWidthBase
     * }
     */
    public static final OfFloat TabMinWidthBase$layout() {
        return TabMinWidthBase$LAYOUT;
    }

    private static final long TabMinWidthBase$OFFSET = $LAYOUT.byteOffset(groupElement("TabMinWidthBase"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float TabMinWidthBase
     * }
     */
    public static final long TabMinWidthBase$offset() {
        return TabMinWidthBase$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float TabMinWidthBase
     * }
     */
    public static float TabMinWidthBase(MemorySegment struct) {
        return struct.get(TabMinWidthBase$LAYOUT, TabMinWidthBase$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float TabMinWidthBase
     * }
     */
    public static void TabMinWidthBase(MemorySegment struct, float fieldValue) {
        struct.set(TabMinWidthBase$LAYOUT, TabMinWidthBase$OFFSET, fieldValue);
    }

    private static final OfFloat TabMinWidthShrink$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("TabMinWidthShrink"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float TabMinWidthShrink
     * }
     */
    public static final OfFloat TabMinWidthShrink$layout() {
        return TabMinWidthShrink$LAYOUT;
    }

    private static final long TabMinWidthShrink$OFFSET = $LAYOUT.byteOffset(groupElement("TabMinWidthShrink"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float TabMinWidthShrink
     * }
     */
    public static final long TabMinWidthShrink$offset() {
        return TabMinWidthShrink$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float TabMinWidthShrink
     * }
     */
    public static float TabMinWidthShrink(MemorySegment struct) {
        return struct.get(TabMinWidthShrink$LAYOUT, TabMinWidthShrink$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float TabMinWidthShrink
     * }
     */
    public static void TabMinWidthShrink(MemorySegment struct, float fieldValue) {
        struct.set(TabMinWidthShrink$LAYOUT, TabMinWidthShrink$OFFSET, fieldValue);
    }

    private static final OfFloat TabCloseButtonMinWidthSelected$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("TabCloseButtonMinWidthSelected"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float TabCloseButtonMinWidthSelected
     * }
     */
    public static final OfFloat TabCloseButtonMinWidthSelected$layout() {
        return TabCloseButtonMinWidthSelected$LAYOUT;
    }

    private static final long TabCloseButtonMinWidthSelected$OFFSET = $LAYOUT.byteOffset(groupElement("TabCloseButtonMinWidthSelected"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float TabCloseButtonMinWidthSelected
     * }
     */
    public static final long TabCloseButtonMinWidthSelected$offset() {
        return TabCloseButtonMinWidthSelected$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float TabCloseButtonMinWidthSelected
     * }
     */
    public static float TabCloseButtonMinWidthSelected(MemorySegment struct) {
        return struct.get(TabCloseButtonMinWidthSelected$LAYOUT, TabCloseButtonMinWidthSelected$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float TabCloseButtonMinWidthSelected
     * }
     */
    public static void TabCloseButtonMinWidthSelected(MemorySegment struct, float fieldValue) {
        struct.set(TabCloseButtonMinWidthSelected$LAYOUT, TabCloseButtonMinWidthSelected$OFFSET, fieldValue);
    }

    private static final OfFloat TabCloseButtonMinWidthUnselected$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("TabCloseButtonMinWidthUnselected"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float TabCloseButtonMinWidthUnselected
     * }
     */
    public static final OfFloat TabCloseButtonMinWidthUnselected$layout() {
        return TabCloseButtonMinWidthUnselected$LAYOUT;
    }

    private static final long TabCloseButtonMinWidthUnselected$OFFSET = $LAYOUT.byteOffset(groupElement("TabCloseButtonMinWidthUnselected"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float TabCloseButtonMinWidthUnselected
     * }
     */
    public static final long TabCloseButtonMinWidthUnselected$offset() {
        return TabCloseButtonMinWidthUnselected$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float TabCloseButtonMinWidthUnselected
     * }
     */
    public static float TabCloseButtonMinWidthUnselected(MemorySegment struct) {
        return struct.get(TabCloseButtonMinWidthUnselected$LAYOUT, TabCloseButtonMinWidthUnselected$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float TabCloseButtonMinWidthUnselected
     * }
     */
    public static void TabCloseButtonMinWidthUnselected(MemorySegment struct, float fieldValue) {
        struct.set(TabCloseButtonMinWidthUnselected$LAYOUT, TabCloseButtonMinWidthUnselected$OFFSET, fieldValue);
    }

    private static final OfFloat TabBarBorderSize$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("TabBarBorderSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float TabBarBorderSize
     * }
     */
    public static final OfFloat TabBarBorderSize$layout() {
        return TabBarBorderSize$LAYOUT;
    }

    private static final long TabBarBorderSize$OFFSET = $LAYOUT.byteOffset(groupElement("TabBarBorderSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float TabBarBorderSize
     * }
     */
    public static final long TabBarBorderSize$offset() {
        return TabBarBorderSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float TabBarBorderSize
     * }
     */
    public static float TabBarBorderSize(MemorySegment struct) {
        return struct.get(TabBarBorderSize$LAYOUT, TabBarBorderSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float TabBarBorderSize
     * }
     */
    public static void TabBarBorderSize(MemorySegment struct, float fieldValue) {
        struct.set(TabBarBorderSize$LAYOUT, TabBarBorderSize$OFFSET, fieldValue);
    }

    private static final OfFloat TabBarOverlineSize$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("TabBarOverlineSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float TabBarOverlineSize
     * }
     */
    public static final OfFloat TabBarOverlineSize$layout() {
        return TabBarOverlineSize$LAYOUT;
    }

    private static final long TabBarOverlineSize$OFFSET = $LAYOUT.byteOffset(groupElement("TabBarOverlineSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float TabBarOverlineSize
     * }
     */
    public static final long TabBarOverlineSize$offset() {
        return TabBarOverlineSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float TabBarOverlineSize
     * }
     */
    public static float TabBarOverlineSize(MemorySegment struct) {
        return struct.get(TabBarOverlineSize$LAYOUT, TabBarOverlineSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float TabBarOverlineSize
     * }
     */
    public static void TabBarOverlineSize(MemorySegment struct, float fieldValue) {
        struct.set(TabBarOverlineSize$LAYOUT, TabBarOverlineSize$OFFSET, fieldValue);
    }

    private static final OfFloat TableAngledHeadersAngle$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("TableAngledHeadersAngle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float TableAngledHeadersAngle
     * }
     */
    public static final OfFloat TableAngledHeadersAngle$layout() {
        return TableAngledHeadersAngle$LAYOUT;
    }

    private static final long TableAngledHeadersAngle$OFFSET = $LAYOUT.byteOffset(groupElement("TableAngledHeadersAngle"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float TableAngledHeadersAngle
     * }
     */
    public static final long TableAngledHeadersAngle$offset() {
        return TableAngledHeadersAngle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float TableAngledHeadersAngle
     * }
     */
    public static float TableAngledHeadersAngle(MemorySegment struct) {
        return struct.get(TableAngledHeadersAngle$LAYOUT, TableAngledHeadersAngle$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float TableAngledHeadersAngle
     * }
     */
    public static void TableAngledHeadersAngle(MemorySegment struct, float fieldValue) {
        struct.set(TableAngledHeadersAngle$LAYOUT, TableAngledHeadersAngle$OFFSET, fieldValue);
    }

    private static final GroupLayout TableAngledHeadersTextAlign$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("TableAngledHeadersTextAlign"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec2_c TableAngledHeadersTextAlign
     * }
     */
    public static final GroupLayout TableAngledHeadersTextAlign$layout() {
        return TableAngledHeadersTextAlign$LAYOUT;
    }

    private static final long TableAngledHeadersTextAlign$OFFSET = $LAYOUT.byteOffset(groupElement("TableAngledHeadersTextAlign"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec2_c TableAngledHeadersTextAlign
     * }
     */
    public static final long TableAngledHeadersTextAlign$offset() {
        return TableAngledHeadersTextAlign$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec2_c TableAngledHeadersTextAlign
     * }
     */
    public static MemorySegment TableAngledHeadersTextAlign(MemorySegment struct) {
        return struct.asSlice(TableAngledHeadersTextAlign$OFFSET, TableAngledHeadersTextAlign$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec2_c TableAngledHeadersTextAlign
     * }
     */
    public static void TableAngledHeadersTextAlign(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, TableAngledHeadersTextAlign$OFFSET, TableAngledHeadersTextAlign$LAYOUT.byteSize());
    }

    private static final OfInt TreeLinesFlags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("TreeLinesFlags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImGuiTreeNodeFlags TreeLinesFlags
     * }
     */
    public static final OfInt TreeLinesFlags$layout() {
        return TreeLinesFlags$LAYOUT;
    }

    private static final long TreeLinesFlags$OFFSET = $LAYOUT.byteOffset(groupElement("TreeLinesFlags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImGuiTreeNodeFlags TreeLinesFlags
     * }
     */
    public static final long TreeLinesFlags$offset() {
        return TreeLinesFlags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImGuiTreeNodeFlags TreeLinesFlags
     * }
     */
    public static int TreeLinesFlags(MemorySegment struct) {
        return struct.get(TreeLinesFlags$LAYOUT, TreeLinesFlags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImGuiTreeNodeFlags TreeLinesFlags
     * }
     */
    public static void TreeLinesFlags(MemorySegment struct, int fieldValue) {
        struct.set(TreeLinesFlags$LAYOUT, TreeLinesFlags$OFFSET, fieldValue);
    }

    private static final OfFloat TreeLinesSize$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("TreeLinesSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float TreeLinesSize
     * }
     */
    public static final OfFloat TreeLinesSize$layout() {
        return TreeLinesSize$LAYOUT;
    }

    private static final long TreeLinesSize$OFFSET = $LAYOUT.byteOffset(groupElement("TreeLinesSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float TreeLinesSize
     * }
     */
    public static final long TreeLinesSize$offset() {
        return TreeLinesSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float TreeLinesSize
     * }
     */
    public static float TreeLinesSize(MemorySegment struct) {
        return struct.get(TreeLinesSize$LAYOUT, TreeLinesSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float TreeLinesSize
     * }
     */
    public static void TreeLinesSize(MemorySegment struct, float fieldValue) {
        struct.set(TreeLinesSize$LAYOUT, TreeLinesSize$OFFSET, fieldValue);
    }

    private static final OfFloat TreeLinesRounding$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("TreeLinesRounding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float TreeLinesRounding
     * }
     */
    public static final OfFloat TreeLinesRounding$layout() {
        return TreeLinesRounding$LAYOUT;
    }

    private static final long TreeLinesRounding$OFFSET = $LAYOUT.byteOffset(groupElement("TreeLinesRounding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float TreeLinesRounding
     * }
     */
    public static final long TreeLinesRounding$offset() {
        return TreeLinesRounding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float TreeLinesRounding
     * }
     */
    public static float TreeLinesRounding(MemorySegment struct) {
        return struct.get(TreeLinesRounding$LAYOUT, TreeLinesRounding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float TreeLinesRounding
     * }
     */
    public static void TreeLinesRounding(MemorySegment struct, float fieldValue) {
        struct.set(TreeLinesRounding$LAYOUT, TreeLinesRounding$OFFSET, fieldValue);
    }

    private static final OfFloat DragDropTargetRounding$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("DragDropTargetRounding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float DragDropTargetRounding
     * }
     */
    public static final OfFloat DragDropTargetRounding$layout() {
        return DragDropTargetRounding$LAYOUT;
    }

    private static final long DragDropTargetRounding$OFFSET = $LAYOUT.byteOffset(groupElement("DragDropTargetRounding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float DragDropTargetRounding
     * }
     */
    public static final long DragDropTargetRounding$offset() {
        return DragDropTargetRounding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float DragDropTargetRounding
     * }
     */
    public static float DragDropTargetRounding(MemorySegment struct) {
        return struct.get(DragDropTargetRounding$LAYOUT, DragDropTargetRounding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float DragDropTargetRounding
     * }
     */
    public static void DragDropTargetRounding(MemorySegment struct, float fieldValue) {
        struct.set(DragDropTargetRounding$LAYOUT, DragDropTargetRounding$OFFSET, fieldValue);
    }

    private static final OfFloat DragDropTargetBorderSize$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("DragDropTargetBorderSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float DragDropTargetBorderSize
     * }
     */
    public static final OfFloat DragDropTargetBorderSize$layout() {
        return DragDropTargetBorderSize$LAYOUT;
    }

    private static final long DragDropTargetBorderSize$OFFSET = $LAYOUT.byteOffset(groupElement("DragDropTargetBorderSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float DragDropTargetBorderSize
     * }
     */
    public static final long DragDropTargetBorderSize$offset() {
        return DragDropTargetBorderSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float DragDropTargetBorderSize
     * }
     */
    public static float DragDropTargetBorderSize(MemorySegment struct) {
        return struct.get(DragDropTargetBorderSize$LAYOUT, DragDropTargetBorderSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float DragDropTargetBorderSize
     * }
     */
    public static void DragDropTargetBorderSize(MemorySegment struct, float fieldValue) {
        struct.set(DragDropTargetBorderSize$LAYOUT, DragDropTargetBorderSize$OFFSET, fieldValue);
    }

    private static final OfFloat DragDropTargetPadding$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("DragDropTargetPadding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float DragDropTargetPadding
     * }
     */
    public static final OfFloat DragDropTargetPadding$layout() {
        return DragDropTargetPadding$LAYOUT;
    }

    private static final long DragDropTargetPadding$OFFSET = $LAYOUT.byteOffset(groupElement("DragDropTargetPadding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float DragDropTargetPadding
     * }
     */
    public static final long DragDropTargetPadding$offset() {
        return DragDropTargetPadding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float DragDropTargetPadding
     * }
     */
    public static float DragDropTargetPadding(MemorySegment struct) {
        return struct.get(DragDropTargetPadding$LAYOUT, DragDropTargetPadding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float DragDropTargetPadding
     * }
     */
    public static void DragDropTargetPadding(MemorySegment struct, float fieldValue) {
        struct.set(DragDropTargetPadding$LAYOUT, DragDropTargetPadding$OFFSET, fieldValue);
    }

    private static final OfFloat ColorMarkerSize$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("ColorMarkerSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float ColorMarkerSize
     * }
     */
    public static final OfFloat ColorMarkerSize$layout() {
        return ColorMarkerSize$LAYOUT;
    }

    private static final long ColorMarkerSize$OFFSET = $LAYOUT.byteOffset(groupElement("ColorMarkerSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float ColorMarkerSize
     * }
     */
    public static final long ColorMarkerSize$offset() {
        return ColorMarkerSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float ColorMarkerSize
     * }
     */
    public static float ColorMarkerSize(MemorySegment struct) {
        return struct.get(ColorMarkerSize$LAYOUT, ColorMarkerSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float ColorMarkerSize
     * }
     */
    public static void ColorMarkerSize(MemorySegment struct, float fieldValue) {
        struct.set(ColorMarkerSize$LAYOUT, ColorMarkerSize$OFFSET, fieldValue);
    }

    private static final OfInt ColorButtonPosition$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ColorButtonPosition"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImGuiDir ColorButtonPosition
     * }
     */
    public static final OfInt ColorButtonPosition$layout() {
        return ColorButtonPosition$LAYOUT;
    }

    private static final long ColorButtonPosition$OFFSET = $LAYOUT.byteOffset(groupElement("ColorButtonPosition"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImGuiDir ColorButtonPosition
     * }
     */
    public static final long ColorButtonPosition$offset() {
        return ColorButtonPosition$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImGuiDir ColorButtonPosition
     * }
     */
    public static int ColorButtonPosition(MemorySegment struct) {
        return struct.get(ColorButtonPosition$LAYOUT, ColorButtonPosition$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImGuiDir ColorButtonPosition
     * }
     */
    public static void ColorButtonPosition(MemorySegment struct, int fieldValue) {
        struct.set(ColorButtonPosition$LAYOUT, ColorButtonPosition$OFFSET, fieldValue);
    }

    private static final GroupLayout ButtonTextAlign$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("ButtonTextAlign"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec2_c ButtonTextAlign
     * }
     */
    public static final GroupLayout ButtonTextAlign$layout() {
        return ButtonTextAlign$LAYOUT;
    }

    private static final long ButtonTextAlign$OFFSET = $LAYOUT.byteOffset(groupElement("ButtonTextAlign"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec2_c ButtonTextAlign
     * }
     */
    public static final long ButtonTextAlign$offset() {
        return ButtonTextAlign$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec2_c ButtonTextAlign
     * }
     */
    public static MemorySegment ButtonTextAlign(MemorySegment struct) {
        return struct.asSlice(ButtonTextAlign$OFFSET, ButtonTextAlign$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec2_c ButtonTextAlign
     * }
     */
    public static void ButtonTextAlign(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ButtonTextAlign$OFFSET, ButtonTextAlign$LAYOUT.byteSize());
    }

    private static final GroupLayout SelectableTextAlign$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("SelectableTextAlign"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec2_c SelectableTextAlign
     * }
     */
    public static final GroupLayout SelectableTextAlign$layout() {
        return SelectableTextAlign$LAYOUT;
    }

    private static final long SelectableTextAlign$OFFSET = $LAYOUT.byteOffset(groupElement("SelectableTextAlign"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec2_c SelectableTextAlign
     * }
     */
    public static final long SelectableTextAlign$offset() {
        return SelectableTextAlign$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec2_c SelectableTextAlign
     * }
     */
    public static MemorySegment SelectableTextAlign(MemorySegment struct) {
        return struct.asSlice(SelectableTextAlign$OFFSET, SelectableTextAlign$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec2_c SelectableTextAlign
     * }
     */
    public static void SelectableTextAlign(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, SelectableTextAlign$OFFSET, SelectableTextAlign$LAYOUT.byteSize());
    }

    private static final OfFloat SeparatorTextBorderSize$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("SeparatorTextBorderSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float SeparatorTextBorderSize
     * }
     */
    public static final OfFloat SeparatorTextBorderSize$layout() {
        return SeparatorTextBorderSize$LAYOUT;
    }

    private static final long SeparatorTextBorderSize$OFFSET = $LAYOUT.byteOffset(groupElement("SeparatorTextBorderSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float SeparatorTextBorderSize
     * }
     */
    public static final long SeparatorTextBorderSize$offset() {
        return SeparatorTextBorderSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float SeparatorTextBorderSize
     * }
     */
    public static float SeparatorTextBorderSize(MemorySegment struct) {
        return struct.get(SeparatorTextBorderSize$LAYOUT, SeparatorTextBorderSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float SeparatorTextBorderSize
     * }
     */
    public static void SeparatorTextBorderSize(MemorySegment struct, float fieldValue) {
        struct.set(SeparatorTextBorderSize$LAYOUT, SeparatorTextBorderSize$OFFSET, fieldValue);
    }

    private static final GroupLayout SeparatorTextAlign$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("SeparatorTextAlign"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec2_c SeparatorTextAlign
     * }
     */
    public static final GroupLayout SeparatorTextAlign$layout() {
        return SeparatorTextAlign$LAYOUT;
    }

    private static final long SeparatorTextAlign$OFFSET = $LAYOUT.byteOffset(groupElement("SeparatorTextAlign"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec2_c SeparatorTextAlign
     * }
     */
    public static final long SeparatorTextAlign$offset() {
        return SeparatorTextAlign$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec2_c SeparatorTextAlign
     * }
     */
    public static MemorySegment SeparatorTextAlign(MemorySegment struct) {
        return struct.asSlice(SeparatorTextAlign$OFFSET, SeparatorTextAlign$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec2_c SeparatorTextAlign
     * }
     */
    public static void SeparatorTextAlign(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, SeparatorTextAlign$OFFSET, SeparatorTextAlign$LAYOUT.byteSize());
    }

    private static final GroupLayout SeparatorTextPadding$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("SeparatorTextPadding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec2_c SeparatorTextPadding
     * }
     */
    public static final GroupLayout SeparatorTextPadding$layout() {
        return SeparatorTextPadding$LAYOUT;
    }

    private static final long SeparatorTextPadding$OFFSET = $LAYOUT.byteOffset(groupElement("SeparatorTextPadding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec2_c SeparatorTextPadding
     * }
     */
    public static final long SeparatorTextPadding$offset() {
        return SeparatorTextPadding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec2_c SeparatorTextPadding
     * }
     */
    public static MemorySegment SeparatorTextPadding(MemorySegment struct) {
        return struct.asSlice(SeparatorTextPadding$OFFSET, SeparatorTextPadding$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec2_c SeparatorTextPadding
     * }
     */
    public static void SeparatorTextPadding(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, SeparatorTextPadding$OFFSET, SeparatorTextPadding$LAYOUT.byteSize());
    }

    private static final GroupLayout DisplayWindowPadding$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("DisplayWindowPadding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec2_c DisplayWindowPadding
     * }
     */
    public static final GroupLayout DisplayWindowPadding$layout() {
        return DisplayWindowPadding$LAYOUT;
    }

    private static final long DisplayWindowPadding$OFFSET = $LAYOUT.byteOffset(groupElement("DisplayWindowPadding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec2_c DisplayWindowPadding
     * }
     */
    public static final long DisplayWindowPadding$offset() {
        return DisplayWindowPadding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec2_c DisplayWindowPadding
     * }
     */
    public static MemorySegment DisplayWindowPadding(MemorySegment struct) {
        return struct.asSlice(DisplayWindowPadding$OFFSET, DisplayWindowPadding$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec2_c DisplayWindowPadding
     * }
     */
    public static void DisplayWindowPadding(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, DisplayWindowPadding$OFFSET, DisplayWindowPadding$LAYOUT.byteSize());
    }

    private static final GroupLayout DisplaySafeAreaPadding$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("DisplaySafeAreaPadding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec2_c DisplaySafeAreaPadding
     * }
     */
    public static final GroupLayout DisplaySafeAreaPadding$layout() {
        return DisplaySafeAreaPadding$LAYOUT;
    }

    private static final long DisplaySafeAreaPadding$OFFSET = $LAYOUT.byteOffset(groupElement("DisplaySafeAreaPadding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec2_c DisplaySafeAreaPadding
     * }
     */
    public static final long DisplaySafeAreaPadding$offset() {
        return DisplaySafeAreaPadding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec2_c DisplaySafeAreaPadding
     * }
     */
    public static MemorySegment DisplaySafeAreaPadding(MemorySegment struct) {
        return struct.asSlice(DisplaySafeAreaPadding$OFFSET, DisplaySafeAreaPadding$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec2_c DisplaySafeAreaPadding
     * }
     */
    public static void DisplaySafeAreaPadding(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, DisplaySafeAreaPadding$OFFSET, DisplaySafeAreaPadding$LAYOUT.byteSize());
    }

    private static final OfFloat MouseCursorScale$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("MouseCursorScale"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float MouseCursorScale
     * }
     */
    public static final OfFloat MouseCursorScale$layout() {
        return MouseCursorScale$LAYOUT;
    }

    private static final long MouseCursorScale$OFFSET = $LAYOUT.byteOffset(groupElement("MouseCursorScale"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float MouseCursorScale
     * }
     */
    public static final long MouseCursorScale$offset() {
        return MouseCursorScale$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float MouseCursorScale
     * }
     */
    public static float MouseCursorScale(MemorySegment struct) {
        return struct.get(MouseCursorScale$LAYOUT, MouseCursorScale$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float MouseCursorScale
     * }
     */
    public static void MouseCursorScale(MemorySegment struct, float fieldValue) {
        struct.set(MouseCursorScale$LAYOUT, MouseCursorScale$OFFSET, fieldValue);
    }

    private static final OfBoolean AntiAliasedLines$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("AntiAliasedLines"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool AntiAliasedLines
     * }
     */
    public static final OfBoolean AntiAliasedLines$layout() {
        return AntiAliasedLines$LAYOUT;
    }

    private static final long AntiAliasedLines$OFFSET = $LAYOUT.byteOffset(groupElement("AntiAliasedLines"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool AntiAliasedLines
     * }
     */
    public static final long AntiAliasedLines$offset() {
        return AntiAliasedLines$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool AntiAliasedLines
     * }
     */
    public static boolean AntiAliasedLines(MemorySegment struct) {
        return struct.get(AntiAliasedLines$LAYOUT, AntiAliasedLines$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool AntiAliasedLines
     * }
     */
    public static void AntiAliasedLines(MemorySegment struct, boolean fieldValue) {
        struct.set(AntiAliasedLines$LAYOUT, AntiAliasedLines$OFFSET, fieldValue);
    }

    private static final OfBoolean AntiAliasedLinesUseTex$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("AntiAliasedLinesUseTex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool AntiAliasedLinesUseTex
     * }
     */
    public static final OfBoolean AntiAliasedLinesUseTex$layout() {
        return AntiAliasedLinesUseTex$LAYOUT;
    }

    private static final long AntiAliasedLinesUseTex$OFFSET = $LAYOUT.byteOffset(groupElement("AntiAliasedLinesUseTex"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool AntiAliasedLinesUseTex
     * }
     */
    public static final long AntiAliasedLinesUseTex$offset() {
        return AntiAliasedLinesUseTex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool AntiAliasedLinesUseTex
     * }
     */
    public static boolean AntiAliasedLinesUseTex(MemorySegment struct) {
        return struct.get(AntiAliasedLinesUseTex$LAYOUT, AntiAliasedLinesUseTex$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool AntiAliasedLinesUseTex
     * }
     */
    public static void AntiAliasedLinesUseTex(MemorySegment struct, boolean fieldValue) {
        struct.set(AntiAliasedLinesUseTex$LAYOUT, AntiAliasedLinesUseTex$OFFSET, fieldValue);
    }

    private static final OfBoolean AntiAliasedFill$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("AntiAliasedFill"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool AntiAliasedFill
     * }
     */
    public static final OfBoolean AntiAliasedFill$layout() {
        return AntiAliasedFill$LAYOUT;
    }

    private static final long AntiAliasedFill$OFFSET = $LAYOUT.byteOffset(groupElement("AntiAliasedFill"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool AntiAliasedFill
     * }
     */
    public static final long AntiAliasedFill$offset() {
        return AntiAliasedFill$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool AntiAliasedFill
     * }
     */
    public static boolean AntiAliasedFill(MemorySegment struct) {
        return struct.get(AntiAliasedFill$LAYOUT, AntiAliasedFill$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool AntiAliasedFill
     * }
     */
    public static void AntiAliasedFill(MemorySegment struct, boolean fieldValue) {
        struct.set(AntiAliasedFill$LAYOUT, AntiAliasedFill$OFFSET, fieldValue);
    }

    private static final OfFloat CurveTessellationTol$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("CurveTessellationTol"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float CurveTessellationTol
     * }
     */
    public static final OfFloat CurveTessellationTol$layout() {
        return CurveTessellationTol$LAYOUT;
    }

    private static final long CurveTessellationTol$OFFSET = $LAYOUT.byteOffset(groupElement("CurveTessellationTol"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float CurveTessellationTol
     * }
     */
    public static final long CurveTessellationTol$offset() {
        return CurveTessellationTol$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float CurveTessellationTol
     * }
     */
    public static float CurveTessellationTol(MemorySegment struct) {
        return struct.get(CurveTessellationTol$LAYOUT, CurveTessellationTol$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float CurveTessellationTol
     * }
     */
    public static void CurveTessellationTol(MemorySegment struct, float fieldValue) {
        struct.set(CurveTessellationTol$LAYOUT, CurveTessellationTol$OFFSET, fieldValue);
    }

    private static final OfFloat CircleTessellationMaxError$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("CircleTessellationMaxError"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float CircleTessellationMaxError
     * }
     */
    public static final OfFloat CircleTessellationMaxError$layout() {
        return CircleTessellationMaxError$LAYOUT;
    }

    private static final long CircleTessellationMaxError$OFFSET = $LAYOUT.byteOffset(groupElement("CircleTessellationMaxError"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float CircleTessellationMaxError
     * }
     */
    public static final long CircleTessellationMaxError$offset() {
        return CircleTessellationMaxError$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float CircleTessellationMaxError
     * }
     */
    public static float CircleTessellationMaxError(MemorySegment struct) {
        return struct.get(CircleTessellationMaxError$LAYOUT, CircleTessellationMaxError$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float CircleTessellationMaxError
     * }
     */
    public static void CircleTessellationMaxError(MemorySegment struct, float fieldValue) {
        struct.set(CircleTessellationMaxError$LAYOUT, CircleTessellationMaxError$OFFSET, fieldValue);
    }

    private static final SequenceLayout Colors$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("Colors"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVec4_c Colors[60]
     * }
     */
    public static final SequenceLayout Colors$layout() {
        return Colors$LAYOUT;
    }

    private static final long Colors$OFFSET = $LAYOUT.byteOffset(groupElement("Colors"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVec4_c Colors[60]
     * }
     */
    public static final long Colors$offset() {
        return Colors$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVec4_c Colors[60]
     * }
     */
    public static MemorySegment Colors(MemorySegment struct) {
        return struct.asSlice(Colors$OFFSET, Colors$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVec4_c Colors[60]
     * }
     */
    public static void Colors(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, Colors$OFFSET, Colors$LAYOUT.byteSize());
    }

    private static long[] Colors$DIMS = { 60 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * ImVec4_c Colors[60]
     * }
     */
    public static long[] Colors$dimensions() {
        return Colors$DIMS;
    }
    private static final MethodHandle Colors$ELEM_HANDLE = Colors$LAYOUT.sliceHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * ImVec4_c Colors[60]
     * }
     */
    public static MemorySegment Colors(MemorySegment struct, long index0) {
        try {
            return (MemorySegment)Colors$ELEM_HANDLE.invokeExact(struct, Colors$OFFSET, index0);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * ImVec4_c Colors[60]
     * }
     */
    public static void Colors(MemorySegment struct, long index0, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, Colors(struct, index0), 0L, ImVec4_c.layout().byteSize());
    }

    private static final OfFloat HoverStationaryDelay$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("HoverStationaryDelay"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float HoverStationaryDelay
     * }
     */
    public static final OfFloat HoverStationaryDelay$layout() {
        return HoverStationaryDelay$LAYOUT;
    }

    private static final long HoverStationaryDelay$OFFSET = $LAYOUT.byteOffset(groupElement("HoverStationaryDelay"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float HoverStationaryDelay
     * }
     */
    public static final long HoverStationaryDelay$offset() {
        return HoverStationaryDelay$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float HoverStationaryDelay
     * }
     */
    public static float HoverStationaryDelay(MemorySegment struct) {
        return struct.get(HoverStationaryDelay$LAYOUT, HoverStationaryDelay$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float HoverStationaryDelay
     * }
     */
    public static void HoverStationaryDelay(MemorySegment struct, float fieldValue) {
        struct.set(HoverStationaryDelay$LAYOUT, HoverStationaryDelay$OFFSET, fieldValue);
    }

    private static final OfFloat HoverDelayShort$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("HoverDelayShort"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float HoverDelayShort
     * }
     */
    public static final OfFloat HoverDelayShort$layout() {
        return HoverDelayShort$LAYOUT;
    }

    private static final long HoverDelayShort$OFFSET = $LAYOUT.byteOffset(groupElement("HoverDelayShort"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float HoverDelayShort
     * }
     */
    public static final long HoverDelayShort$offset() {
        return HoverDelayShort$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float HoverDelayShort
     * }
     */
    public static float HoverDelayShort(MemorySegment struct) {
        return struct.get(HoverDelayShort$LAYOUT, HoverDelayShort$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float HoverDelayShort
     * }
     */
    public static void HoverDelayShort(MemorySegment struct, float fieldValue) {
        struct.set(HoverDelayShort$LAYOUT, HoverDelayShort$OFFSET, fieldValue);
    }

    private static final OfFloat HoverDelayNormal$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("HoverDelayNormal"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float HoverDelayNormal
     * }
     */
    public static final OfFloat HoverDelayNormal$layout() {
        return HoverDelayNormal$LAYOUT;
    }

    private static final long HoverDelayNormal$OFFSET = $LAYOUT.byteOffset(groupElement("HoverDelayNormal"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float HoverDelayNormal
     * }
     */
    public static final long HoverDelayNormal$offset() {
        return HoverDelayNormal$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float HoverDelayNormal
     * }
     */
    public static float HoverDelayNormal(MemorySegment struct) {
        return struct.get(HoverDelayNormal$LAYOUT, HoverDelayNormal$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float HoverDelayNormal
     * }
     */
    public static void HoverDelayNormal(MemorySegment struct, float fieldValue) {
        struct.set(HoverDelayNormal$LAYOUT, HoverDelayNormal$OFFSET, fieldValue);
    }

    private static final OfInt HoverFlagsForTooltipMouse$LAYOUT = (OfInt)$LAYOUT.select(groupElement("HoverFlagsForTooltipMouse"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImGuiHoveredFlags HoverFlagsForTooltipMouse
     * }
     */
    public static final OfInt HoverFlagsForTooltipMouse$layout() {
        return HoverFlagsForTooltipMouse$LAYOUT;
    }

    private static final long HoverFlagsForTooltipMouse$OFFSET = $LAYOUT.byteOffset(groupElement("HoverFlagsForTooltipMouse"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImGuiHoveredFlags HoverFlagsForTooltipMouse
     * }
     */
    public static final long HoverFlagsForTooltipMouse$offset() {
        return HoverFlagsForTooltipMouse$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImGuiHoveredFlags HoverFlagsForTooltipMouse
     * }
     */
    public static int HoverFlagsForTooltipMouse(MemorySegment struct) {
        return struct.get(HoverFlagsForTooltipMouse$LAYOUT, HoverFlagsForTooltipMouse$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImGuiHoveredFlags HoverFlagsForTooltipMouse
     * }
     */
    public static void HoverFlagsForTooltipMouse(MemorySegment struct, int fieldValue) {
        struct.set(HoverFlagsForTooltipMouse$LAYOUT, HoverFlagsForTooltipMouse$OFFSET, fieldValue);
    }

    private static final OfInt HoverFlagsForTooltipNav$LAYOUT = (OfInt)$LAYOUT.select(groupElement("HoverFlagsForTooltipNav"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImGuiHoveredFlags HoverFlagsForTooltipNav
     * }
     */
    public static final OfInt HoverFlagsForTooltipNav$layout() {
        return HoverFlagsForTooltipNav$LAYOUT;
    }

    private static final long HoverFlagsForTooltipNav$OFFSET = $LAYOUT.byteOffset(groupElement("HoverFlagsForTooltipNav"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImGuiHoveredFlags HoverFlagsForTooltipNav
     * }
     */
    public static final long HoverFlagsForTooltipNav$offset() {
        return HoverFlagsForTooltipNav$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImGuiHoveredFlags HoverFlagsForTooltipNav
     * }
     */
    public static int HoverFlagsForTooltipNav(MemorySegment struct) {
        return struct.get(HoverFlagsForTooltipNav$LAYOUT, HoverFlagsForTooltipNav$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImGuiHoveredFlags HoverFlagsForTooltipNav
     * }
     */
    public static void HoverFlagsForTooltipNav(MemorySegment struct, int fieldValue) {
        struct.set(HoverFlagsForTooltipNav$LAYOUT, HoverFlagsForTooltipNav$OFFSET, fieldValue);
    }

    private static final OfFloat _MainScale$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("_MainScale"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float _MainScale
     * }
     */
    public static final OfFloat _MainScale$layout() {
        return _MainScale$LAYOUT;
    }

    private static final long _MainScale$OFFSET = $LAYOUT.byteOffset(groupElement("_MainScale"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float _MainScale
     * }
     */
    public static final long _MainScale$offset() {
        return _MainScale$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float _MainScale
     * }
     */
    public static float _MainScale(MemorySegment struct) {
        return struct.get(_MainScale$LAYOUT, _MainScale$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float _MainScale
     * }
     */
    public static void _MainScale(MemorySegment struct, float fieldValue) {
        struct.set(_MainScale$LAYOUT, _MainScale$OFFSET, fieldValue);
    }

    private static final OfFloat _NextFrameFontSizeBase$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("_NextFrameFontSizeBase"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float _NextFrameFontSizeBase
     * }
     */
    public static final OfFloat _NextFrameFontSizeBase$layout() {
        return _NextFrameFontSizeBase$LAYOUT;
    }

    private static final long _NextFrameFontSizeBase$OFFSET = $LAYOUT.byteOffset(groupElement("_NextFrameFontSizeBase"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float _NextFrameFontSizeBase
     * }
     */
    public static final long _NextFrameFontSizeBase$offset() {
        return _NextFrameFontSizeBase$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float _NextFrameFontSizeBase
     * }
     */
    public static float _NextFrameFontSizeBase(MemorySegment struct) {
        return struct.get(_NextFrameFontSizeBase$LAYOUT, _NextFrameFontSizeBase$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float _NextFrameFontSizeBase
     * }
     */
    public static void _NextFrameFontSizeBase(MemorySegment struct, float fieldValue) {
        struct.set(_NextFrameFontSizeBase$LAYOUT, _NextFrameFontSizeBase$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

