// Generated by jextract

package net.bplo.libs.jimgui.binding;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ImGuiDeactivatedItemData {
 *     ImGuiID ID;
 *     int ElapseFrame;
 *     bool HasBeenEditedBefore;
 *     bool IsAlive;
 * }
 * }
 */
public class ImGuiDeactivatedItemData {

    ImGuiDeactivatedItemData() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        cimgui_h.C_INT.withName("ID"),
        cimgui_h.C_INT.withName("ElapseFrame"),
        cimgui_h.C_BOOL.withName("HasBeenEditedBefore"),
        cimgui_h.C_BOOL.withName("IsAlive"),
        MemoryLayout.paddingLayout(2)
    ).withName("ImGuiDeactivatedItemData");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt ID$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ID"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImGuiID ID
     * }
     */
    public static final OfInt ID$layout() {
        return ID$LAYOUT;
    }

    private static final long ID$OFFSET = $LAYOUT.byteOffset(groupElement("ID"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImGuiID ID
     * }
     */
    public static final long ID$offset() {
        return ID$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImGuiID ID
     * }
     */
    public static int ID(MemorySegment struct) {
        return struct.get(ID$LAYOUT, ID$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImGuiID ID
     * }
     */
    public static void ID(MemorySegment struct, int fieldValue) {
        struct.set(ID$LAYOUT, ID$OFFSET, fieldValue);
    }

    private static final OfInt ElapseFrame$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ElapseFrame"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int ElapseFrame
     * }
     */
    public static final OfInt ElapseFrame$layout() {
        return ElapseFrame$LAYOUT;
    }

    private static final long ElapseFrame$OFFSET = $LAYOUT.byteOffset(groupElement("ElapseFrame"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int ElapseFrame
     * }
     */
    public static final long ElapseFrame$offset() {
        return ElapseFrame$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int ElapseFrame
     * }
     */
    public static int ElapseFrame(MemorySegment struct) {
        return struct.get(ElapseFrame$LAYOUT, ElapseFrame$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int ElapseFrame
     * }
     */
    public static void ElapseFrame(MemorySegment struct, int fieldValue) {
        struct.set(ElapseFrame$LAYOUT, ElapseFrame$OFFSET, fieldValue);
    }

    private static final OfBoolean HasBeenEditedBefore$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("HasBeenEditedBefore"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool HasBeenEditedBefore
     * }
     */
    public static final OfBoolean HasBeenEditedBefore$layout() {
        return HasBeenEditedBefore$LAYOUT;
    }

    private static final long HasBeenEditedBefore$OFFSET = $LAYOUT.byteOffset(groupElement("HasBeenEditedBefore"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool HasBeenEditedBefore
     * }
     */
    public static final long HasBeenEditedBefore$offset() {
        return HasBeenEditedBefore$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool HasBeenEditedBefore
     * }
     */
    public static boolean HasBeenEditedBefore(MemorySegment struct) {
        return struct.get(HasBeenEditedBefore$LAYOUT, HasBeenEditedBefore$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool HasBeenEditedBefore
     * }
     */
    public static void HasBeenEditedBefore(MemorySegment struct, boolean fieldValue) {
        struct.set(HasBeenEditedBefore$LAYOUT, HasBeenEditedBefore$OFFSET, fieldValue);
    }

    private static final OfBoolean IsAlive$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("IsAlive"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool IsAlive
     * }
     */
    public static final OfBoolean IsAlive$layout() {
        return IsAlive$LAYOUT;
    }

    private static final long IsAlive$OFFSET = $LAYOUT.byteOffset(groupElement("IsAlive"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool IsAlive
     * }
     */
    public static final long IsAlive$offset() {
        return IsAlive$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool IsAlive
     * }
     */
    public static boolean IsAlive(MemorySegment struct) {
        return struct.get(IsAlive$LAYOUT, IsAlive$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool IsAlive
     * }
     */
    public static void IsAlive(MemorySegment struct, boolean fieldValue) {
        struct.set(IsAlive$LAYOUT, IsAlive$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

