// Generated by jextract

package net.bplo.libs.jimgui.binding;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ImGuiNextItemData {
 *     ImGuiNextItemDataFlags HasFlags;
 *     ImGuiItemFlags ItemFlags;
 *     ImGuiID FocusScopeId;
 *     ImGuiSelectionUserData SelectionUserData;
 *     float Width;
 *     ImGuiKeyChord Shortcut;
 *     ImGuiInputFlags ShortcutFlags;
 *     bool OpenVal;
 *     ImU8 OpenCond;
 *     ImGuiDataTypeStorage RefVal;
 *     ImGuiID StorageId;
 *     ImU32 ColorMarker;
 * }
 * }
 */
public class ImGuiNextItemData {

    ImGuiNextItemData() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        cimgui_h.C_INT.withName("HasFlags"),
        cimgui_h.C_INT.withName("ItemFlags"),
        cimgui_h.C_INT.withName("FocusScopeId"),
        MemoryLayout.paddingLayout(4),
        cimgui_h.C_LONG_LONG.withName("SelectionUserData"),
        cimgui_h.C_FLOAT.withName("Width"),
        cimgui_h.C_INT.withName("Shortcut"),
        cimgui_h.C_INT.withName("ShortcutFlags"),
        cimgui_h.C_BOOL.withName("OpenVal"),
        cimgui_h.C_CHAR.withName("OpenCond"),
        ImGuiDataTypeStorage.layout().withName("RefVal"),
        MemoryLayout.paddingLayout(2),
        cimgui_h.C_INT.withName("StorageId"),
        cimgui_h.C_INT.withName("ColorMarker")
    ).withName("ImGuiNextItemData");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt HasFlags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("HasFlags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImGuiNextItemDataFlags HasFlags
     * }
     */
    public static final OfInt HasFlags$layout() {
        return HasFlags$LAYOUT;
    }

    private static final long HasFlags$OFFSET = $LAYOUT.byteOffset(groupElement("HasFlags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImGuiNextItemDataFlags HasFlags
     * }
     */
    public static final long HasFlags$offset() {
        return HasFlags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImGuiNextItemDataFlags HasFlags
     * }
     */
    public static int HasFlags(MemorySegment struct) {
        return struct.get(HasFlags$LAYOUT, HasFlags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImGuiNextItemDataFlags HasFlags
     * }
     */
    public static void HasFlags(MemorySegment struct, int fieldValue) {
        struct.set(HasFlags$LAYOUT, HasFlags$OFFSET, fieldValue);
    }

    private static final OfInt ItemFlags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ItemFlags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImGuiItemFlags ItemFlags
     * }
     */
    public static final OfInt ItemFlags$layout() {
        return ItemFlags$LAYOUT;
    }

    private static final long ItemFlags$OFFSET = $LAYOUT.byteOffset(groupElement("ItemFlags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImGuiItemFlags ItemFlags
     * }
     */
    public static final long ItemFlags$offset() {
        return ItemFlags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImGuiItemFlags ItemFlags
     * }
     */
    public static int ItemFlags(MemorySegment struct) {
        return struct.get(ItemFlags$LAYOUT, ItemFlags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImGuiItemFlags ItemFlags
     * }
     */
    public static void ItemFlags(MemorySegment struct, int fieldValue) {
        struct.set(ItemFlags$LAYOUT, ItemFlags$OFFSET, fieldValue);
    }

    private static final OfInt FocusScopeId$LAYOUT = (OfInt)$LAYOUT.select(groupElement("FocusScopeId"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImGuiID FocusScopeId
     * }
     */
    public static final OfInt FocusScopeId$layout() {
        return FocusScopeId$LAYOUT;
    }

    private static final long FocusScopeId$OFFSET = $LAYOUT.byteOffset(groupElement("FocusScopeId"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImGuiID FocusScopeId
     * }
     */
    public static final long FocusScopeId$offset() {
        return FocusScopeId$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImGuiID FocusScopeId
     * }
     */
    public static int FocusScopeId(MemorySegment struct) {
        return struct.get(FocusScopeId$LAYOUT, FocusScopeId$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImGuiID FocusScopeId
     * }
     */
    public static void FocusScopeId(MemorySegment struct, int fieldValue) {
        struct.set(FocusScopeId$LAYOUT, FocusScopeId$OFFSET, fieldValue);
    }

    private static final OfLong SelectionUserData$LAYOUT = (OfLong)$LAYOUT.select(groupElement("SelectionUserData"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImGuiSelectionUserData SelectionUserData
     * }
     */
    public static final OfLong SelectionUserData$layout() {
        return SelectionUserData$LAYOUT;
    }

    private static final long SelectionUserData$OFFSET = $LAYOUT.byteOffset(groupElement("SelectionUserData"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImGuiSelectionUserData SelectionUserData
     * }
     */
    public static final long SelectionUserData$offset() {
        return SelectionUserData$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImGuiSelectionUserData SelectionUserData
     * }
     */
    public static long SelectionUserData(MemorySegment struct) {
        return struct.get(SelectionUserData$LAYOUT, SelectionUserData$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImGuiSelectionUserData SelectionUserData
     * }
     */
    public static void SelectionUserData(MemorySegment struct, long fieldValue) {
        struct.set(SelectionUserData$LAYOUT, SelectionUserData$OFFSET, fieldValue);
    }

    private static final OfFloat Width$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("Width"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float Width
     * }
     */
    public static final OfFloat Width$layout() {
        return Width$LAYOUT;
    }

    private static final long Width$OFFSET = $LAYOUT.byteOffset(groupElement("Width"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float Width
     * }
     */
    public static final long Width$offset() {
        return Width$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float Width
     * }
     */
    public static float Width(MemorySegment struct) {
        return struct.get(Width$LAYOUT, Width$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float Width
     * }
     */
    public static void Width(MemorySegment struct, float fieldValue) {
        struct.set(Width$LAYOUT, Width$OFFSET, fieldValue);
    }

    private static final OfInt Shortcut$LAYOUT = (OfInt)$LAYOUT.select(groupElement("Shortcut"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImGuiKeyChord Shortcut
     * }
     */
    public static final OfInt Shortcut$layout() {
        return Shortcut$LAYOUT;
    }

    private static final long Shortcut$OFFSET = $LAYOUT.byteOffset(groupElement("Shortcut"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImGuiKeyChord Shortcut
     * }
     */
    public static final long Shortcut$offset() {
        return Shortcut$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImGuiKeyChord Shortcut
     * }
     */
    public static int Shortcut(MemorySegment struct) {
        return struct.get(Shortcut$LAYOUT, Shortcut$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImGuiKeyChord Shortcut
     * }
     */
    public static void Shortcut(MemorySegment struct, int fieldValue) {
        struct.set(Shortcut$LAYOUT, Shortcut$OFFSET, fieldValue);
    }

    private static final OfInt ShortcutFlags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ShortcutFlags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImGuiInputFlags ShortcutFlags
     * }
     */
    public static final OfInt ShortcutFlags$layout() {
        return ShortcutFlags$LAYOUT;
    }

    private static final long ShortcutFlags$OFFSET = $LAYOUT.byteOffset(groupElement("ShortcutFlags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImGuiInputFlags ShortcutFlags
     * }
     */
    public static final long ShortcutFlags$offset() {
        return ShortcutFlags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImGuiInputFlags ShortcutFlags
     * }
     */
    public static int ShortcutFlags(MemorySegment struct) {
        return struct.get(ShortcutFlags$LAYOUT, ShortcutFlags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImGuiInputFlags ShortcutFlags
     * }
     */
    public static void ShortcutFlags(MemorySegment struct, int fieldValue) {
        struct.set(ShortcutFlags$LAYOUT, ShortcutFlags$OFFSET, fieldValue);
    }

    private static final OfBoolean OpenVal$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("OpenVal"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool OpenVal
     * }
     */
    public static final OfBoolean OpenVal$layout() {
        return OpenVal$LAYOUT;
    }

    private static final long OpenVal$OFFSET = $LAYOUT.byteOffset(groupElement("OpenVal"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool OpenVal
     * }
     */
    public static final long OpenVal$offset() {
        return OpenVal$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool OpenVal
     * }
     */
    public static boolean OpenVal(MemorySegment struct) {
        return struct.get(OpenVal$LAYOUT, OpenVal$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool OpenVal
     * }
     */
    public static void OpenVal(MemorySegment struct, boolean fieldValue) {
        struct.set(OpenVal$LAYOUT, OpenVal$OFFSET, fieldValue);
    }

    private static final OfByte OpenCond$LAYOUT = (OfByte)$LAYOUT.select(groupElement("OpenCond"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImU8 OpenCond
     * }
     */
    public static final OfByte OpenCond$layout() {
        return OpenCond$LAYOUT;
    }

    private static final long OpenCond$OFFSET = $LAYOUT.byteOffset(groupElement("OpenCond"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImU8 OpenCond
     * }
     */
    public static final long OpenCond$offset() {
        return OpenCond$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImU8 OpenCond
     * }
     */
    public static byte OpenCond(MemorySegment struct) {
        return struct.get(OpenCond$LAYOUT, OpenCond$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImU8 OpenCond
     * }
     */
    public static void OpenCond(MemorySegment struct, byte fieldValue) {
        struct.set(OpenCond$LAYOUT, OpenCond$OFFSET, fieldValue);
    }

    private static final GroupLayout RefVal$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("RefVal"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImGuiDataTypeStorage RefVal
     * }
     */
    public static final GroupLayout RefVal$layout() {
        return RefVal$LAYOUT;
    }

    private static final long RefVal$OFFSET = $LAYOUT.byteOffset(groupElement("RefVal"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImGuiDataTypeStorage RefVal
     * }
     */
    public static final long RefVal$offset() {
        return RefVal$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImGuiDataTypeStorage RefVal
     * }
     */
    public static MemorySegment RefVal(MemorySegment struct) {
        return struct.asSlice(RefVal$OFFSET, RefVal$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImGuiDataTypeStorage RefVal
     * }
     */
    public static void RefVal(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, RefVal$OFFSET, RefVal$LAYOUT.byteSize());
    }

    private static final OfInt StorageId$LAYOUT = (OfInt)$LAYOUT.select(groupElement("StorageId"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImGuiID StorageId
     * }
     */
    public static final OfInt StorageId$layout() {
        return StorageId$LAYOUT;
    }

    private static final long StorageId$OFFSET = $LAYOUT.byteOffset(groupElement("StorageId"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImGuiID StorageId
     * }
     */
    public static final long StorageId$offset() {
        return StorageId$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImGuiID StorageId
     * }
     */
    public static int StorageId(MemorySegment struct) {
        return struct.get(StorageId$LAYOUT, StorageId$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImGuiID StorageId
     * }
     */
    public static void StorageId(MemorySegment struct, int fieldValue) {
        struct.set(StorageId$LAYOUT, StorageId$OFFSET, fieldValue);
    }

    private static final OfInt ColorMarker$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ColorMarker"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImU32 ColorMarker
     * }
     */
    public static final OfInt ColorMarker$layout() {
        return ColorMarker$LAYOUT;
    }

    private static final long ColorMarker$OFFSET = $LAYOUT.byteOffset(groupElement("ColorMarker"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImU32 ColorMarker
     * }
     */
    public static final long ColorMarker$offset() {
        return ColorMarker$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImU32 ColorMarker
     * }
     */
    public static int ColorMarker(MemorySegment struct) {
        return struct.get(ColorMarker$LAYOUT, ColorMarker$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImU32 ColorMarker
     * }
     */
    public static void ColorMarker(MemorySegment struct, int fieldValue) {
        struct.set(ColorMarker$LAYOUT, ColorMarker$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

