// Generated by jextract

package net.bplo.libs.jimgui.binding;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct ImRect_c {
 *     ImVec2_c Min;
 *     ImVec2_c Max;
 * } ImRect
 * }
 */
public class ImRect extends ImRect_c {

    ImRect() {
        // Should not be called directly
    }
}

