// Generated by jextract

package net.bplo.libs.jimgui.binding;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ImTextureData {
 *     int UniqueID;
 *     ImTextureStatus Status;
 *     void *BackendUserData;
 *     ImTextureID TexID;
 *     ImTextureFormat Format;
 *     int Width;
 *     int Height;
 *     int BytesPerPixel;
 *     unsigned char *Pixels;
 *     ImTextureRect UsedRect;
 *     ImTextureRect UpdateRect;
 *     ImVector_ImTextureRect Updates;
 *     int UnusedFrames;
 *     unsigned short RefCount;
 *     bool UseColors;
 *     bool WantDestroyNextFrame;
 * }
 * }
 */
public class ImTextureData {

    ImTextureData() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        cimgui_h.C_INT.withName("UniqueID"),
        cimgui_h.C_INT.withName("Status"),
        cimgui_h.C_POINTER.withName("BackendUserData"),
        cimgui_h.C_LONG_LONG.withName("TexID"),
        cimgui_h.C_INT.withName("Format"),
        cimgui_h.C_INT.withName("Width"),
        cimgui_h.C_INT.withName("Height"),
        cimgui_h.C_INT.withName("BytesPerPixel"),
        cimgui_h.C_POINTER.withName("Pixels"),
        ImTextureRect.layout().withName("UsedRect"),
        ImTextureRect.layout().withName("UpdateRect"),
        ImVector_ImTextureRect.layout().withName("Updates"),
        cimgui_h.C_INT.withName("UnusedFrames"),
        cimgui_h.C_SHORT.withName("RefCount"),
        cimgui_h.C_BOOL.withName("UseColors"),
        cimgui_h.C_BOOL.withName("WantDestroyNextFrame")
    ).withName("ImTextureData");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt UniqueID$LAYOUT = (OfInt)$LAYOUT.select(groupElement("UniqueID"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int UniqueID
     * }
     */
    public static final OfInt UniqueID$layout() {
        return UniqueID$LAYOUT;
    }

    private static final long UniqueID$OFFSET = $LAYOUT.byteOffset(groupElement("UniqueID"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int UniqueID
     * }
     */
    public static final long UniqueID$offset() {
        return UniqueID$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int UniqueID
     * }
     */
    public static int UniqueID(MemorySegment struct) {
        return struct.get(UniqueID$LAYOUT, UniqueID$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int UniqueID
     * }
     */
    public static void UniqueID(MemorySegment struct, int fieldValue) {
        struct.set(UniqueID$LAYOUT, UniqueID$OFFSET, fieldValue);
    }

    private static final OfInt Status$LAYOUT = (OfInt)$LAYOUT.select(groupElement("Status"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImTextureStatus Status
     * }
     */
    public static final OfInt Status$layout() {
        return Status$LAYOUT;
    }

    private static final long Status$OFFSET = $LAYOUT.byteOffset(groupElement("Status"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImTextureStatus Status
     * }
     */
    public static final long Status$offset() {
        return Status$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImTextureStatus Status
     * }
     */
    public static int Status(MemorySegment struct) {
        return struct.get(Status$LAYOUT, Status$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImTextureStatus Status
     * }
     */
    public static void Status(MemorySegment struct, int fieldValue) {
        struct.set(Status$LAYOUT, Status$OFFSET, fieldValue);
    }

    private static final AddressLayout BackendUserData$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("BackendUserData"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *BackendUserData
     * }
     */
    public static final AddressLayout BackendUserData$layout() {
        return BackendUserData$LAYOUT;
    }

    private static final long BackendUserData$OFFSET = $LAYOUT.byteOffset(groupElement("BackendUserData"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *BackendUserData
     * }
     */
    public static final long BackendUserData$offset() {
        return BackendUserData$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *BackendUserData
     * }
     */
    public static MemorySegment BackendUserData(MemorySegment struct) {
        return struct.get(BackendUserData$LAYOUT, BackendUserData$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *BackendUserData
     * }
     */
    public static void BackendUserData(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(BackendUserData$LAYOUT, BackendUserData$OFFSET, fieldValue);
    }

    private static final OfLong TexID$LAYOUT = (OfLong)$LAYOUT.select(groupElement("TexID"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImTextureID TexID
     * }
     */
    public static final OfLong TexID$layout() {
        return TexID$LAYOUT;
    }

    private static final long TexID$OFFSET = $LAYOUT.byteOffset(groupElement("TexID"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImTextureID TexID
     * }
     */
    public static final long TexID$offset() {
        return TexID$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImTextureID TexID
     * }
     */
    public static long TexID(MemorySegment struct) {
        return struct.get(TexID$LAYOUT, TexID$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImTextureID TexID
     * }
     */
    public static void TexID(MemorySegment struct, long fieldValue) {
        struct.set(TexID$LAYOUT, TexID$OFFSET, fieldValue);
    }

    private static final OfInt Format$LAYOUT = (OfInt)$LAYOUT.select(groupElement("Format"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImTextureFormat Format
     * }
     */
    public static final OfInt Format$layout() {
        return Format$LAYOUT;
    }

    private static final long Format$OFFSET = $LAYOUT.byteOffset(groupElement("Format"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImTextureFormat Format
     * }
     */
    public static final long Format$offset() {
        return Format$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImTextureFormat Format
     * }
     */
    public static int Format(MemorySegment struct) {
        return struct.get(Format$LAYOUT, Format$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImTextureFormat Format
     * }
     */
    public static void Format(MemorySegment struct, int fieldValue) {
        struct.set(Format$LAYOUT, Format$OFFSET, fieldValue);
    }

    private static final OfInt Width$LAYOUT = (OfInt)$LAYOUT.select(groupElement("Width"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int Width
     * }
     */
    public static final OfInt Width$layout() {
        return Width$LAYOUT;
    }

    private static final long Width$OFFSET = $LAYOUT.byteOffset(groupElement("Width"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int Width
     * }
     */
    public static final long Width$offset() {
        return Width$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int Width
     * }
     */
    public static int Width(MemorySegment struct) {
        return struct.get(Width$LAYOUT, Width$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int Width
     * }
     */
    public static void Width(MemorySegment struct, int fieldValue) {
        struct.set(Width$LAYOUT, Width$OFFSET, fieldValue);
    }

    private static final OfInt Height$LAYOUT = (OfInt)$LAYOUT.select(groupElement("Height"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int Height
     * }
     */
    public static final OfInt Height$layout() {
        return Height$LAYOUT;
    }

    private static final long Height$OFFSET = $LAYOUT.byteOffset(groupElement("Height"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int Height
     * }
     */
    public static final long Height$offset() {
        return Height$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int Height
     * }
     */
    public static int Height(MemorySegment struct) {
        return struct.get(Height$LAYOUT, Height$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int Height
     * }
     */
    public static void Height(MemorySegment struct, int fieldValue) {
        struct.set(Height$LAYOUT, Height$OFFSET, fieldValue);
    }

    private static final OfInt BytesPerPixel$LAYOUT = (OfInt)$LAYOUT.select(groupElement("BytesPerPixel"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int BytesPerPixel
     * }
     */
    public static final OfInt BytesPerPixel$layout() {
        return BytesPerPixel$LAYOUT;
    }

    private static final long BytesPerPixel$OFFSET = $LAYOUT.byteOffset(groupElement("BytesPerPixel"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int BytesPerPixel
     * }
     */
    public static final long BytesPerPixel$offset() {
        return BytesPerPixel$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int BytesPerPixel
     * }
     */
    public static int BytesPerPixel(MemorySegment struct) {
        return struct.get(BytesPerPixel$LAYOUT, BytesPerPixel$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int BytesPerPixel
     * }
     */
    public static void BytesPerPixel(MemorySegment struct, int fieldValue) {
        struct.set(BytesPerPixel$LAYOUT, BytesPerPixel$OFFSET, fieldValue);
    }

    private static final AddressLayout Pixels$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("Pixels"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char *Pixels
     * }
     */
    public static final AddressLayout Pixels$layout() {
        return Pixels$LAYOUT;
    }

    private static final long Pixels$OFFSET = $LAYOUT.byteOffset(groupElement("Pixels"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char *Pixels
     * }
     */
    public static final long Pixels$offset() {
        return Pixels$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char *Pixels
     * }
     */
    public static MemorySegment Pixels(MemorySegment struct) {
        return struct.get(Pixels$LAYOUT, Pixels$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char *Pixels
     * }
     */
    public static void Pixels(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(Pixels$LAYOUT, Pixels$OFFSET, fieldValue);
    }

    private static final GroupLayout UsedRect$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("UsedRect"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImTextureRect UsedRect
     * }
     */
    public static final GroupLayout UsedRect$layout() {
        return UsedRect$LAYOUT;
    }

    private static final long UsedRect$OFFSET = $LAYOUT.byteOffset(groupElement("UsedRect"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImTextureRect UsedRect
     * }
     */
    public static final long UsedRect$offset() {
        return UsedRect$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImTextureRect UsedRect
     * }
     */
    public static MemorySegment UsedRect(MemorySegment struct) {
        return struct.asSlice(UsedRect$OFFSET, UsedRect$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImTextureRect UsedRect
     * }
     */
    public static void UsedRect(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, UsedRect$OFFSET, UsedRect$LAYOUT.byteSize());
    }

    private static final GroupLayout UpdateRect$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("UpdateRect"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImTextureRect UpdateRect
     * }
     */
    public static final GroupLayout UpdateRect$layout() {
        return UpdateRect$LAYOUT;
    }

    private static final long UpdateRect$OFFSET = $LAYOUT.byteOffset(groupElement("UpdateRect"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImTextureRect UpdateRect
     * }
     */
    public static final long UpdateRect$offset() {
        return UpdateRect$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImTextureRect UpdateRect
     * }
     */
    public static MemorySegment UpdateRect(MemorySegment struct) {
        return struct.asSlice(UpdateRect$OFFSET, UpdateRect$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImTextureRect UpdateRect
     * }
     */
    public static void UpdateRect(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, UpdateRect$OFFSET, UpdateRect$LAYOUT.byteSize());
    }

    private static final GroupLayout Updates$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("Updates"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ImVector_ImTextureRect Updates
     * }
     */
    public static final GroupLayout Updates$layout() {
        return Updates$LAYOUT;
    }

    private static final long Updates$OFFSET = $LAYOUT.byteOffset(groupElement("Updates"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ImVector_ImTextureRect Updates
     * }
     */
    public static final long Updates$offset() {
        return Updates$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ImVector_ImTextureRect Updates
     * }
     */
    public static MemorySegment Updates(MemorySegment struct) {
        return struct.asSlice(Updates$OFFSET, Updates$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ImVector_ImTextureRect Updates
     * }
     */
    public static void Updates(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, Updates$OFFSET, Updates$LAYOUT.byteSize());
    }

    private static final OfInt UnusedFrames$LAYOUT = (OfInt)$LAYOUT.select(groupElement("UnusedFrames"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int UnusedFrames
     * }
     */
    public static final OfInt UnusedFrames$layout() {
        return UnusedFrames$LAYOUT;
    }

    private static final long UnusedFrames$OFFSET = $LAYOUT.byteOffset(groupElement("UnusedFrames"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int UnusedFrames
     * }
     */
    public static final long UnusedFrames$offset() {
        return UnusedFrames$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int UnusedFrames
     * }
     */
    public static int UnusedFrames(MemorySegment struct) {
        return struct.get(UnusedFrames$LAYOUT, UnusedFrames$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int UnusedFrames
     * }
     */
    public static void UnusedFrames(MemorySegment struct, int fieldValue) {
        struct.set(UnusedFrames$LAYOUT, UnusedFrames$OFFSET, fieldValue);
    }

    private static final OfShort RefCount$LAYOUT = (OfShort)$LAYOUT.select(groupElement("RefCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned short RefCount
     * }
     */
    public static final OfShort RefCount$layout() {
        return RefCount$LAYOUT;
    }

    private static final long RefCount$OFFSET = $LAYOUT.byteOffset(groupElement("RefCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned short RefCount
     * }
     */
    public static final long RefCount$offset() {
        return RefCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned short RefCount
     * }
     */
    public static short RefCount(MemorySegment struct) {
        return struct.get(RefCount$LAYOUT, RefCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned short RefCount
     * }
     */
    public static void RefCount(MemorySegment struct, short fieldValue) {
        struct.set(RefCount$LAYOUT, RefCount$OFFSET, fieldValue);
    }

    private static final OfBoolean UseColors$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("UseColors"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool UseColors
     * }
     */
    public static final OfBoolean UseColors$layout() {
        return UseColors$LAYOUT;
    }

    private static final long UseColors$OFFSET = $LAYOUT.byteOffset(groupElement("UseColors"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool UseColors
     * }
     */
    public static final long UseColors$offset() {
        return UseColors$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool UseColors
     * }
     */
    public static boolean UseColors(MemorySegment struct) {
        return struct.get(UseColors$LAYOUT, UseColors$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool UseColors
     * }
     */
    public static void UseColors(MemorySegment struct, boolean fieldValue) {
        struct.set(UseColors$LAYOUT, UseColors$OFFSET, fieldValue);
    }

    private static final OfBoolean WantDestroyNextFrame$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("WantDestroyNextFrame"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool WantDestroyNextFrame
     * }
     */
    public static final OfBoolean WantDestroyNextFrame$layout() {
        return WantDestroyNextFrame$LAYOUT;
    }

    private static final long WantDestroyNextFrame$OFFSET = $LAYOUT.byteOffset(groupElement("WantDestroyNextFrame"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool WantDestroyNextFrame
     * }
     */
    public static final long WantDestroyNextFrame$offset() {
        return WantDestroyNextFrame$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool WantDestroyNextFrame
     * }
     */
    public static boolean WantDestroyNextFrame(MemorySegment struct) {
        return struct.get(WantDestroyNextFrame$LAYOUT, WantDestroyNextFrame$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool WantDestroyNextFrame
     * }
     */
    public static void WantDestroyNextFrame(MemorySegment struct, boolean fieldValue) {
        struct.set(WantDestroyNextFrame$LAYOUT, WantDestroyNextFrame$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

