// Generated by jextract

package net.bplo.libs.jimgui.binding;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct ImVec2_c {
 *     float x;
 *     float y;
 * } ImVec2
 * }
 */
public class ImVec2 extends ImVec2_c {

    ImVec2() {
        // Should not be called directly
    }
}

